// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\gameinfo.proto
package com.wesocial.apollo.protocol.protobuf.gameinfo;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.INT32;
import static com.squareup.wire.Message.Datatype.INT64;

public final class GameRankInfo extends Message {
  private static final long serialVersionUID = 0L;

  public static final Integer DEFAULT_GAME_ID = 0;
  public static final Integer DEFAULT_WEEK_RANK = 0;
  public static final Integer DEFAULT_WEEK_SCORE = 0;
  public static final Long DEFAULT_WEEK_UPDATE_TIME = 0L;
  public static final Integer DEFAULT_HISTORY_RANK = 0;
  public static final Integer DEFAULT_HISTORY_SCORE = 0;
  public static final Long DEFAULT_HISTORY_UPDATE_TIME = 0L;

  @ProtoField(tag = 1, type = INT32)
  public final Integer game_id;

  /**
   * 游戏id
   */
  @ProtoField(tag = 2)
  public final GameInfo game_info;

  /**
   * 游戏信息
   */
  @ProtoField(tag = 3, type = INT32)
  public final Integer week_rank;

  /**
   * 用户周分数排名
   */
  @ProtoField(tag = 4, type = INT32)
  public final Integer week_score;

  /**
   * 用户周分数
   */
  @ProtoField(tag = 5, type = INT64)
  public final Long week_update_time;

  /**
   * 分数更新时间
   */
  @ProtoField(tag = 6, type = INT32)
  public final Integer history_rank;

  /**
   * 用户历史最高分的排名
   */
  @ProtoField(tag = 7, type = INT32)
  public final Integer history_score;

  /**
   * 用户历史最高分
   */
  @ProtoField(tag = 8, type = INT64)
  public final Long history_update_time;

  public GameRankInfo(Integer game_id, GameInfo game_info, Integer week_rank, Integer week_score, Long week_update_time, Integer history_rank, Integer history_score, Long history_update_time) {
    this.game_id = game_id;
    this.game_info = game_info;
    this.week_rank = week_rank;
    this.week_score = week_score;
    this.week_update_time = week_update_time;
    this.history_rank = history_rank;
    this.history_score = history_score;
    this.history_update_time = history_update_time;
  }

  private GameRankInfo(Builder builder) {
    this(builder.game_id, builder.game_info, builder.week_rank, builder.week_score, builder.week_update_time, builder.history_rank, builder.history_score, builder.history_update_time);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof GameRankInfo)) return false;
    GameRankInfo o = (GameRankInfo) other;
    return equals(game_id, o.game_id)
        && equals(game_info, o.game_info)
        && equals(week_rank, o.week_rank)
        && equals(week_score, o.week_score)
        && equals(week_update_time, o.week_update_time)
        && equals(history_rank, o.history_rank)
        && equals(history_score, o.history_score)
        && equals(history_update_time, o.history_update_time);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = game_id != null ? game_id.hashCode() : 0;
      result = result * 37 + (game_info != null ? game_info.hashCode() : 0);
      result = result * 37 + (week_rank != null ? week_rank.hashCode() : 0);
      result = result * 37 + (week_score != null ? week_score.hashCode() : 0);
      result = result * 37 + (week_update_time != null ? week_update_time.hashCode() : 0);
      result = result * 37 + (history_rank != null ? history_rank.hashCode() : 0);
      result = result * 37 + (history_score != null ? history_score.hashCode() : 0);
      result = result * 37 + (history_update_time != null ? history_update_time.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<GameRankInfo> {

    public Integer game_id;
    public GameInfo game_info;
    public Integer week_rank;
    public Integer week_score;
    public Long week_update_time;
    public Integer history_rank;
    public Integer history_score;
    public Long history_update_time;

    public Builder() {
    }

    public Builder(GameRankInfo message) {
      super(message);
      if (message == null) return;
      this.game_id = message.game_id;
      this.game_info = message.game_info;
      this.week_rank = message.week_rank;
      this.week_score = message.week_score;
      this.week_update_time = message.week_update_time;
      this.history_rank = message.history_rank;
      this.history_score = message.history_score;
      this.history_update_time = message.history_update_time;
    }

    public Builder game_id(Integer game_id) {
      this.game_id = game_id;
      return this;
    }

    /**
     * 游戏id
     */
    public Builder game_info(GameInfo game_info) {
      this.game_info = game_info;
      return this;
    }

    /**
     * 游戏信息
     */
    public Builder week_rank(Integer week_rank) {
      this.week_rank = week_rank;
      return this;
    }

    /**
     * 用户周分数排名
     */
    public Builder week_score(Integer week_score) {
      this.week_score = week_score;
      return this;
    }

    /**
     * 用户周分数
     */
    public Builder week_update_time(Long week_update_time) {
      this.week_update_time = week_update_time;
      return this;
    }

    /**
     * 分数更新时间
     */
    public Builder history_rank(Integer history_rank) {
      this.history_rank = history_rank;
      return this;
    }

    /**
     * 用户历史最高分的排名
     */
    public Builder history_score(Integer history_score) {
      this.history_score = history_score;
      return this;
    }

    /**
     * 用户历史最高分
     */
    public Builder history_update_time(Long history_update_time) {
      this.history_update_time = history_update_time;
      return this;
    }

    @Override
    public GameRankInfo build() {
      return new GameRankInfo(this);
    }
  }
}
