// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\gameinfo.proto
package com.wesocial.apollo.protocol.protobuf.gameinfo;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;
import okio.ByteString;

import static com.squareup.wire.Message.Datatype.BYTES;

public final class GetGameInfoRsp extends Message {
  private static final long serialVersionUID = 0L;

  public static final ByteString DEFAULT_RESERVED_BUF = ByteString.EMPTY;

  @ProtoField(tag = 1, type = BYTES)
  public final ByteString reserved_buf;

  /**
   * 服务端使用，客户端忽略
   */
  @ProtoField(tag = 2)
  public final GameInfo game_info;

  public GetGameInfoRsp(ByteString reserved_buf, GameInfo game_info) {
    this.reserved_buf = reserved_buf;
    this.game_info = game_info;
  }

  private GetGameInfoRsp(Builder builder) {
    this(builder.reserved_buf, builder.game_info);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof GetGameInfoRsp)) return false;
    GetGameInfoRsp o = (GetGameInfoRsp) other;
    return equals(reserved_buf, o.reserved_buf)
        && equals(game_info, o.game_info);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = reserved_buf != null ? reserved_buf.hashCode() : 0;
      result = result * 37 + (game_info != null ? game_info.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<GetGameInfoRsp> {

    public ByteString reserved_buf;
    public GameInfo game_info;

    public Builder() {
    }

    public Builder(GetGameInfoRsp message) {
      super(message);
      if (message == null) return;
      this.reserved_buf = message.reserved_buf;
      this.game_info = message.game_info;
    }

    public Builder reserved_buf(ByteString reserved_buf) {
      this.reserved_buf = reserved_buf;
      return this;
    }

    /**
     * 服务端使用，客户端忽略
     */
    public Builder game_info(GameInfo game_info) {
      this.game_info = game_info;
      return this;
    }

    @Override
    public GetGameInfoRsp build() {
      return new GetGameInfoRsp(this);
    }
  }
}
