// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\gameinfo.proto
package com.wesocial.apollo.protocol.protobuf.gameinfo;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;
import java.util.Collections;
import java.util.List;
import okio.ByteString;

import static com.squareup.wire.Message.Datatype.BYTES;
import static com.squareup.wire.Message.Datatype.INT32;
import static com.squareup.wire.Message.Label.REPEATED;

public final class GetRecommendGameListRsp extends Message {
  private static final long serialVersionUID = 0L;

  public static final ByteString DEFAULT_RESERVED_BUF = ByteString.EMPTY;
  public static final List<RecommendGameInfo> DEFAULT_RECOMMEND_GAME_LIST = Collections.emptyList();
  public static final Integer DEFAULT_TOTAL_NUM = 0;

  @ProtoField(tag = 1, type = BYTES)
  public final ByteString reserved_buf;

  /**
   * 服务端使用，客户端忽略
   */
  @ProtoField(tag = 2, label = REPEATED, messageType = RecommendGameInfo.class)
  public final List<RecommendGameInfo> recommend_game_list;

  /**
   * 游戏列表
   */
  @ProtoField(tag = 3, type = INT32)
  public final Integer total_num;

  public GetRecommendGameListRsp(ByteString reserved_buf, List<RecommendGameInfo> recommend_game_list, Integer total_num) {
    this.reserved_buf = reserved_buf;
    this.recommend_game_list = immutableCopyOf(recommend_game_list);
    this.total_num = total_num;
  }

  private GetRecommendGameListRsp(Builder builder) {
    this(builder.reserved_buf, builder.recommend_game_list, builder.total_num);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof GetRecommendGameListRsp)) return false;
    GetRecommendGameListRsp o = (GetRecommendGameListRsp) other;
    return equals(reserved_buf, o.reserved_buf)
        && equals(recommend_game_list, o.recommend_game_list)
        && equals(total_num, o.total_num);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = reserved_buf != null ? reserved_buf.hashCode() : 0;
      result = result * 37 + (recommend_game_list != null ? recommend_game_list.hashCode() : 1);
      result = result * 37 + (total_num != null ? total_num.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<GetRecommendGameListRsp> {

    public ByteString reserved_buf;
    public List<RecommendGameInfo> recommend_game_list;
    public Integer total_num;

    public Builder() {
    }

    public Builder(GetRecommendGameListRsp message) {
      super(message);
      if (message == null) return;
      this.reserved_buf = message.reserved_buf;
      this.recommend_game_list = copyOf(message.recommend_game_list);
      this.total_num = message.total_num;
    }

    public Builder reserved_buf(ByteString reserved_buf) {
      this.reserved_buf = reserved_buf;
      return this;
    }

    /**
     * 服务端使用，客户端忽略
     */
    public Builder recommend_game_list(List<RecommendGameInfo> recommend_game_list) {
      this.recommend_game_list = checkForNulls(recommend_game_list);
      return this;
    }

    /**
     * 游戏列表
     */
    public Builder total_num(Integer total_num) {
      this.total_num = total_num;
      return this;
    }

    @Override
    public GetRecommendGameListRsp build() {
      return new GetRecommendGameListRsp(this);
    }
  }
}
