// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\gameinfo.proto
package com.wesocial.apollo.protocol.protobuf.gameinfo;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;
import com.wesocial.apollo.protocol.protobuf.profile.AllUserInfo;
import java.util.Collections;
import java.util.List;

import static com.squareup.wire.Message.Datatype.INT32;
import static com.squareup.wire.Message.Label.REPEATED;

public final class RecommendGameInfo extends Message {
  private static final long serialVersionUID = 0L;

  public static final Integer DEFAULT_GAME_ID = 0;
  public static final List<AllUserInfo> DEFAULT_ALL_USER_INFO = Collections.emptyList();
  public static final Integer DEFAULT_PLAYER_NUM = 0;

  @ProtoField(tag = 1, type = INT32)
  public final Integer game_id;

  /**
   * 游戏id
   */
  @ProtoField(tag = 2)
  public final GameInfo game_info;

  /**
   * 游戏信息
   */
  @ProtoField(tag = 3, label = REPEATED, messageType = AllUserInfo.class)
  public final List<AllUserInfo> all_user_info;

  /**
   * 附近在玩的用户
   */
  @ProtoField(tag = 4, type = INT32)
  public final Integer player_num;

  public RecommendGameInfo(Integer game_id, GameInfo game_info, List<AllUserInfo> all_user_info, Integer player_num) {
    this.game_id = game_id;
    this.game_info = game_info;
    this.all_user_info = immutableCopyOf(all_user_info);
    this.player_num = player_num;
  }

  private RecommendGameInfo(Builder builder) {
    this(builder.game_id, builder.game_info, builder.all_user_info, builder.player_num);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof RecommendGameInfo)) return false;
    RecommendGameInfo o = (RecommendGameInfo) other;
    return equals(game_id, o.game_id)
        && equals(game_info, o.game_info)
        && equals(all_user_info, o.all_user_info)
        && equals(player_num, o.player_num);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = game_id != null ? game_id.hashCode() : 0;
      result = result * 37 + (game_info != null ? game_info.hashCode() : 0);
      result = result * 37 + (all_user_info != null ? all_user_info.hashCode() : 1);
      result = result * 37 + (player_num != null ? player_num.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<RecommendGameInfo> {

    public Integer game_id;
    public GameInfo game_info;
    public List<AllUserInfo> all_user_info;
    public Integer player_num;

    public Builder() {
    }

    public Builder(RecommendGameInfo message) {
      super(message);
      if (message == null) return;
      this.game_id = message.game_id;
      this.game_info = message.game_info;
      this.all_user_info = copyOf(message.all_user_info);
      this.player_num = message.player_num;
    }

    public Builder game_id(Integer game_id) {
      this.game_id = game_id;
      return this;
    }

    /**
     * 游戏id
     */
    public Builder game_info(GameInfo game_info) {
      this.game_info = game_info;
      return this;
    }

    /**
     * 游戏信息
     */
    public Builder all_user_info(List<AllUserInfo> all_user_info) {
      this.all_user_info = checkForNulls(all_user_info);
      return this;
    }

    /**
     * 附近在玩的用户
     */
    public Builder player_num(Integer player_num) {
      this.player_num = player_num;
      return this;
    }

    @Override
    public RecommendGameInfo build() {
      return new RecommendGameInfo(this);
    }
  }
}
