// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\gameinfo.proto
package com.wesocial.apollo.protocol.protobuf.gameinfo;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;
import okio.ByteString;

import static com.squareup.wire.Message.Datatype.BYTES;
import static com.squareup.wire.Message.Datatype.INT32;

/**
 * 上报游戏分数 SUBMIT_GAME_SCORE
 */
public final class SubmitGameScoreReq extends Message {
  private static final long serialVersionUID = 0L;

  public static final ByteString DEFAULT_RESERVED_BUF = ByteString.EMPTY;
  public static final Integer DEFAULT_GAME_ID = 0;
  public static final Integer DEFAULT_GAME_SCORE = 0;

  @ProtoField(tag = 1, type = BYTES)
  public final ByteString reserved_buf;

  /**
   * 服务端使用，客户端忽略
   */
  @ProtoField(tag = 2, type = INT32)
  public final Integer game_id;

  /**
   * 游戏id
   */
  @ProtoField(tag = 3, type = INT32)
  public final Integer game_score;

  public SubmitGameScoreReq(ByteString reserved_buf, Integer game_id, Integer game_score) {
    this.reserved_buf = reserved_buf;
    this.game_id = game_id;
    this.game_score = game_score;
  }

  private SubmitGameScoreReq(Builder builder) {
    this(builder.reserved_buf, builder.game_id, builder.game_score);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof SubmitGameScoreReq)) return false;
    SubmitGameScoreReq o = (SubmitGameScoreReq) other;
    return equals(reserved_buf, o.reserved_buf)
        && equals(game_id, o.game_id)
        && equals(game_score, o.game_score);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = reserved_buf != null ? reserved_buf.hashCode() : 0;
      result = result * 37 + (game_id != null ? game_id.hashCode() : 0);
      result = result * 37 + (game_score != null ? game_score.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<SubmitGameScoreReq> {

    public ByteString reserved_buf;
    public Integer game_id;
    public Integer game_score;

    public Builder() {
    }

    public Builder(SubmitGameScoreReq message) {
      super(message);
      if (message == null) return;
      this.reserved_buf = message.reserved_buf;
      this.game_id = message.game_id;
      this.game_score = message.game_score;
    }

    public Builder reserved_buf(ByteString reserved_buf) {
      this.reserved_buf = reserved_buf;
      return this;
    }

    /**
     * 服务端使用，客户端忽略
     */
    public Builder game_id(Integer game_id) {
      this.game_id = game_id;
      return this;
    }

    /**
     * 游戏id
     */
    public Builder game_score(Integer game_score) {
      this.game_score = game_score;
      return this;
    }

    @Override
    public SubmitGameScoreReq build() {
      return new SubmitGameScoreReq(this);
    }
  }
}
