// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\push.proto
package com.wesocial.apollo.protocol.protobuf.push;

import com.squareup.wire.Message;

/**
 * -------------------------------------------------------------
 * 2. 相关基础结构体
 * -------------------------------------------------------------
 */
public final class LoginInfo extends Message {
  private static final long serialVersionUID = 0L;

  public LoginInfo() {
  }

  private LoginInfo(Builder builder) {
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    return other instanceof LoginInfo;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public static final class Builder extends Message.Builder<LoginInfo> {

    public Builder() {
    }

    public Builder(LoginInfo message) {
      super(message);
    }

    @Override
    public LoginInfo build() {
      return new LoginInfo(this);
    }
  }
}
