// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\push.proto
package com.wesocial.apollo.protocol.protobuf.push;

import com.squareup.wire.ProtoEnum;

public enum PushCmd
    implements ProtoEnum {
  kPushHasNewMessage(1),
  /**
   * 有新的好友消息
   */
  kPushHasNewFriends(2),
  /**
   * 有新的好友状态变更
   */
  kPushKickOut(3),
  /**
   * 强制下线
   */
  kPushFriendExpired(4),
  /**
   * 好友失效
   */
  kPUshHasNewFeeds(5),
  /**
   * 有新的动态（可能是评论，点赞等）
   */
  kPushHasNewGreeting(6),
  /**
   * 有新的打招呼
   */
  kPushUserTaskNew(7),
  /**
   * 任务有更新
   */
  kPushGameMatchTimeOut(8),
  /**
   * 游戏匹配超时推送
   */
  kPushGameMatchDone(9),
  /**
   * 游戏匹配成功推送
   */
  kPushGameUpdateMsg(10),
  /**
   * 游戏通知
   */
  kPushPktownUpdateMsg(11);

  private final int value;

  private PushCmd(int value) {
    this.value = value;
  }

  @Override
  public int getValue() {
    return value;
  }
}
