// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\match.proto
package com.wesocial.apollo.protocol.protobuf.match;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;
import java.util.Collections;
import java.util.List;

import static com.squareup.wire.Message.Label.REPEATED;

public final class AI_InnerIdList extends Message {
  private static final long serialVersionUID = 0L;

  public static final List<InnerIdInfo> DEFAULT_LIST = Collections.emptyList();

  @ProtoField(tag = 1, label = REPEATED, messageType = InnerIdInfo.class)
  public final List<InnerIdInfo> list;

  public AI_InnerIdList(List<InnerIdInfo> list) {
    this.list = immutableCopyOf(list);
  }

  private AI_InnerIdList(Builder builder) {
    this(builder.list);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof AI_InnerIdList)) return false;
    return equals(list, ((AI_InnerIdList) other).list);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    return result != 0 ? result : (hashCode = list != null ? list.hashCode() : 1);
  }

  public static final class Builder extends Message.Builder<AI_InnerIdList> {

    public List<InnerIdInfo> list;

    public Builder() {
    }

    public Builder(AI_InnerIdList message) {
      super(message);
      if (message == null) return;
      this.list = copyOf(message.list);
    }

    public Builder list(List<InnerIdInfo> list) {
      this.list = checkForNulls(list);
      return this;
    }

    @Override
    public AI_InnerIdList build() {
      return new AI_InnerIdList(this);
    }
  }
}
