// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\match.proto
package com.wesocial.apollo.protocol.protobuf.match;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;
import java.util.Collections;
import java.util.List;

import static com.squareup.wire.Message.Label.REPEATED;

public final class AllOnlineInfo extends Message {
  private static final long serialVersionUID = 0L;

  public static final List<PlayerOnlineInfo> DEFAULT_ALL_ONLINE_INFO = Collections.emptyList();

  @ProtoField(tag = 1, label = REPEATED, messageType = PlayerOnlineInfo.class)
  public final List<PlayerOnlineInfo> all_online_info;

  public AllOnlineInfo(List<PlayerOnlineInfo> all_online_info) {
    this.all_online_info = immutableCopyOf(all_online_info);
  }

  private AllOnlineInfo(Builder builder) {
    this(builder.all_online_info);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof AllOnlineInfo)) return false;
    return equals(all_online_info, ((AllOnlineInfo) other).all_online_info);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    return result != 0 ? result : (hashCode = all_online_info != null ? all_online_info.hashCode() : 1);
  }

  public static final class Builder extends Message.Builder<AllOnlineInfo> {

    public List<PlayerOnlineInfo> all_online_info;

    public Builder() {
    }

    public Builder(AllOnlineInfo message) {
      super(message);
      if (message == null) return;
      this.all_online_info = copyOf(message.all_online_info);
    }

    public Builder all_online_info(List<PlayerOnlineInfo> all_online_info) {
      this.all_online_info = checkForNulls(all_online_info);
      return this;
    }

    @Override
    public AllOnlineInfo build() {
      return new AllOnlineInfo(this);
    }
  }
}
