// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\match.proto
package com.wesocial.apollo.protocol.protobuf.match;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;
import okio.ByteString;

import static com.squareup.wire.Message.Datatype.BYTES;

public final class CheckTableOnlineRsp extends Message {
  private static final long serialVersionUID = 0L;

  public static final ByteString DEFAULT_RESERVED_BUF = ByteString.EMPTY;

  @ProtoField(tag = 1, type = BYTES)
  public final ByteString reserved_buf;

  /**
   * 服务端使用，客户端忽略
   */
  @ProtoField(tag = 2)
  public final TableOnlineInfo table_online_info;

  public CheckTableOnlineRsp(ByteString reserved_buf, TableOnlineInfo table_online_info) {
    this.reserved_buf = reserved_buf;
    this.table_online_info = table_online_info;
  }

  private CheckTableOnlineRsp(Builder builder) {
    this(builder.reserved_buf, builder.table_online_info);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof CheckTableOnlineRsp)) return false;
    CheckTableOnlineRsp o = (CheckTableOnlineRsp) other;
    return equals(reserved_buf, o.reserved_buf)
        && equals(table_online_info, o.table_online_info);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = reserved_buf != null ? reserved_buf.hashCode() : 0;
      result = result * 37 + (table_online_info != null ? table_online_info.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<CheckTableOnlineRsp> {

    public ByteString reserved_buf;
    public TableOnlineInfo table_online_info;

    public Builder() {
    }

    public Builder(CheckTableOnlineRsp message) {
      super(message);
      if (message == null) return;
      this.reserved_buf = message.reserved_buf;
      this.table_online_info = message.table_online_info;
    }

    public Builder reserved_buf(ByteString reserved_buf) {
      this.reserved_buf = reserved_buf;
      return this;
    }

    /**
     * 服务端使用，客户端忽略
     */
    public Builder table_online_info(TableOnlineInfo table_online_info) {
      this.table_online_info = table_online_info;
      return this;
    }

    @Override
    public CheckTableOnlineRsp build() {
      return new CheckTableOnlineRsp(this);
    }
  }
}
