// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\match.proto
package com.wesocial.apollo.protocol.protobuf.match;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;
import com.wesocial.apollo.protocol.protobuf.game.RouteInfo;
import okio.ByteString;

import static com.squareup.wire.Message.Datatype.BYTES;

/**
 * 查询桌子状态 CHECK_TABLE_ONLINE
 */
public final class CheckTableOnlineReq extends Message {
  private static final long serialVersionUID = 0L;

  public static final ByteString DEFAULT_RESERVED_BUF = ByteString.EMPTY;

  @ProtoField(tag = 1, type = BYTES)
  public final ByteString reserved_buf;

  /**
   * 服务端使用，客户端忽略
   */
  @ProtoField(tag = 2)
  public final RouteInfo route_info;

  public CheckTableOnlineReq(ByteString reserved_buf, RouteInfo route_info) {
    this.reserved_buf = reserved_buf;
    this.route_info = route_info;
  }

  private CheckTableOnlineReq(Builder builder) {
    this(builder.reserved_buf, builder.route_info);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof CheckTableOnlineReq)) return false;
    CheckTableOnlineReq o = (CheckTableOnlineReq) other;
    return equals(reserved_buf, o.reserved_buf)
        && equals(route_info, o.route_info);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = reserved_buf != null ? reserved_buf.hashCode() : 0;
      result = result * 37 + (route_info != null ? route_info.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<CheckTableOnlineReq> {

    public ByteString reserved_buf;
    public RouteInfo route_info;

    public Builder() {
    }

    public Builder(CheckTableOnlineReq message) {
      super(message);
      if (message == null) return;
      this.reserved_buf = message.reserved_buf;
      this.route_info = message.route_info;
    }

    public Builder reserved_buf(ByteString reserved_buf) {
      this.reserved_buf = reserved_buf;
      return this;
    }

    /**
     * 服务端使用，客户端忽略
     */
    public Builder route_info(RouteInfo route_info) {
      this.route_info = route_info;
      return this;
    }

    @Override
    public CheckTableOnlineReq build() {
      return new CheckTableOnlineReq(this);
    }
  }
}
