// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\match.proto
package com.wesocial.apollo.protocol.protobuf.match;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;
import okio.ByteString;

import static com.squareup.wire.Message.Datatype.BYTES;
import static com.squareup.wire.Message.Datatype.INT32;

/**
 * PK场查询匹配详情
 */
public final class CheckMatchInfoReq extends Message {
  private static final long serialVersionUID = 0L;

  public static final ByteString DEFAULT_RESERVED_BUF = ByteString.EMPTY;
  public static final Integer DEFAULT_GAME_ID = 0;
  public static final Integer DEFAULT_GAME_POLICY = 0;

  @ProtoField(tag = 1, type = BYTES)
  public final ByteString reserved_buf;

  /**
   * 服务端使用，客户端忽略
   */
  @ProtoField(tag = 2, type = INT32)
  public final Integer game_id;

  /**
   * 游戏id
   */
  @ProtoField(tag = 3, type = INT32)
  public final Integer game_policy;

  public CheckMatchInfoReq(ByteString reserved_buf, Integer game_id, Integer game_policy) {
    this.reserved_buf = reserved_buf;
    this.game_id = game_id;
    this.game_policy = game_policy;
  }

  private CheckMatchInfoReq(Builder builder) {
    this(builder.reserved_buf, builder.game_id, builder.game_policy);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof CheckMatchInfoReq)) return false;
    CheckMatchInfoReq o = (CheckMatchInfoReq) other;
    return equals(reserved_buf, o.reserved_buf)
        && equals(game_id, o.game_id)
        && equals(game_policy, o.game_policy);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = reserved_buf != null ? reserved_buf.hashCode() : 0;
      result = result * 37 + (game_id != null ? game_id.hashCode() : 0);
      result = result * 37 + (game_policy != null ? game_policy.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<CheckMatchInfoReq> {

    public ByteString reserved_buf;
    public Integer game_id;
    public Integer game_policy;

    public Builder() {
    }

    public Builder(CheckMatchInfoReq message) {
      super(message);
      if (message == null) return;
      this.reserved_buf = message.reserved_buf;
      this.game_id = message.game_id;
      this.game_policy = message.game_policy;
    }

    public Builder reserved_buf(ByteString reserved_buf) {
      this.reserved_buf = reserved_buf;
      return this;
    }

    /**
     * 服务端使用，客户端忽略
     */
    public Builder game_id(Integer game_id) {
      this.game_id = game_id;
      return this;
    }

    /**
     * 游戏id
     */
    public Builder game_policy(Integer game_policy) {
      this.game_policy = game_policy;
      return this;
    }

    @Override
    public CheckMatchInfoReq build() {
      return new CheckMatchInfoReq(this);
    }
  }
}
