// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\match.proto
package com.wesocial.apollo.protocol.protobuf.match;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;
import java.util.Collections;
import java.util.List;

import static com.squareup.wire.Message.Datatype.UINT64;
import static com.squareup.wire.Message.Label.REPEATED;

public final class InnerIdList extends Message {
  private static final long serialVersionUID = 0L;

  public static final List<Long> DEFAULT_INNER_ID_LIST = Collections.emptyList();

  @ProtoField(tag = 1, type = UINT64, label = REPEATED)
  public final List<Long> inner_id_list;

  public InnerIdList(List<Long> inner_id_list) {
    this.inner_id_list = immutableCopyOf(inner_id_list);
  }

  private InnerIdList(Builder builder) {
    this(builder.inner_id_list);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof InnerIdList)) return false;
    return equals(inner_id_list, ((InnerIdList) other).inner_id_list);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    return result != 0 ? result : (hashCode = inner_id_list != null ? inner_id_list.hashCode() : 1);
  }

  public static final class Builder extends Message.Builder<InnerIdList> {

    public List<Long> inner_id_list;

    public Builder() {
    }

    public Builder(InnerIdList message) {
      super(message);
      if (message == null) return;
      this.inner_id_list = copyOf(message.inner_id_list);
    }

    public Builder inner_id_list(List<Long> inner_id_list) {
      this.inner_id_list = checkForNulls(inner_id_list);
      return this;
    }

    @Override
    public InnerIdList build() {
      return new InnerIdList(this);
    }
  }
}
