// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\match.proto
package com.wesocial.apollo.protocol.protobuf.match;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;
import java.util.Collections;
import java.util.List;

import static com.squareup.wire.Message.Label.REPEATED;

public final class Match_GameSvrInfoList extends Message {
  private static final long serialVersionUID = 0L;

  public static final List<Match_GameSvrInfo> DEFAULT_GAMESVR_INFO = Collections.emptyList();

  @ProtoField(tag = 1, label = REPEATED, messageType = Match_GameSvrInfo.class)
  public final List<Match_GameSvrInfo> gamesvr_info;

  public Match_GameSvrInfoList(List<Match_GameSvrInfo> gamesvr_info) {
    this.gamesvr_info = immutableCopyOf(gamesvr_info);
  }

  private Match_GameSvrInfoList(Builder builder) {
    this(builder.gamesvr_info);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof Match_GameSvrInfoList)) return false;
    return equals(gamesvr_info, ((Match_GameSvrInfoList) other).gamesvr_info);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    return result != 0 ? result : (hashCode = gamesvr_info != null ? gamesvr_info.hashCode() : 1);
  }

  public static final class Builder extends Message.Builder<Match_GameSvrInfoList> {

    public List<Match_GameSvrInfo> gamesvr_info;

    public Builder() {
    }

    public Builder(Match_GameSvrInfoList message) {
      super(message);
      if (message == null) return;
      this.gamesvr_info = copyOf(message.gamesvr_info);
    }

    public Builder gamesvr_info(List<Match_GameSvrInfo> gamesvr_info) {
      this.gamesvr_info = checkForNulls(gamesvr_info);
      return this;
    }

    @Override
    public Match_GameSvrInfoList build() {
      return new Match_GameSvrInfoList(this);
    }
  }
}
