// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\match.proto
package com.wesocial.apollo.protocol.protobuf.match;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;
import java.util.Collections;
import java.util.List;

import static com.squareup.wire.Message.Datatype.INT32;
import static com.squareup.wire.Message.Label.REPEATED;

public final class Match_GameInfo extends Message {
  private static final long serialVersionUID = 0L;

  public static final Integer DEFAULT_GAME_ID = 0;
  public static final List<PolicyInfo> DEFAULT_POLICY_INFO = Collections.emptyList();

  @ProtoField(tag = 1, type = INT32)
  public final Integer game_id;

  /**
   * 游戏id
   */
  @ProtoField(tag = 2, label = REPEATED, messageType = PolicyInfo.class)
  public final List<PolicyInfo> policy_info;

  public Match_GameInfo(Integer game_id, List<PolicyInfo> policy_info) {
    this.game_id = game_id;
    this.policy_info = immutableCopyOf(policy_info);
  }

  private Match_GameInfo(Builder builder) {
    this(builder.game_id, builder.policy_info);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof Match_GameInfo)) return false;
    Match_GameInfo o = (Match_GameInfo) other;
    return equals(game_id, o.game_id)
        && equals(policy_info, o.policy_info);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = game_id != null ? game_id.hashCode() : 0;
      result = result * 37 + (policy_info != null ? policy_info.hashCode() : 1);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<Match_GameInfo> {

    public Integer game_id;
    public List<PolicyInfo> policy_info;

    public Builder() {
    }

    public Builder(Match_GameInfo message) {
      super(message);
      if (message == null) return;
      this.game_id = message.game_id;
      this.policy_info = copyOf(message.policy_info);
    }

    public Builder game_id(Integer game_id) {
      this.game_id = game_id;
      return this;
    }

    /**
     * 游戏id
     */
    public Builder policy_info(List<PolicyInfo> policy_info) {
      this.policy_info = checkForNulls(policy_info);
      return this;
    }

    @Override
    public Match_GameInfo build() {
      return new Match_GameInfo(this);
    }
  }
}
