// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\match.proto
package com.wesocial.apollo.protocol.protobuf.match;

import com.squareup.wire.ProtoEnum;

public enum MultiMatch_Status
    implements ProtoEnum {
  kMultiMatchAcceptOk(1),
  /**
   * 匹配成功
   */
  kMultiMatchAcceptFail(2);

  private final int value;

  private MultiMatch_Status(int value) {
    this.value = value;
  }

  @Override
  public int getValue() {
    return value;
  }
}
