// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\match.proto
package com.wesocial.apollo.protocol.protobuf.match;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;
import com.wesocial.apollo.protocol.protobuf.game.RouteInfo;
import okio.ByteString;

import static com.squareup.wire.Message.Datatype.BYTES;
import static com.squareup.wire.Message.Datatype.INT32;

public final class MultiMatchRsp extends Message {
  private static final long serialVersionUID = 0L;

  public static final ByteString DEFAULT_RESERVED_BUF = ByteString.EMPTY;
  public static final Integer DEFAULT_MATCH_RESULT = 0;

  @ProtoField(tag = 1, type = BYTES)
  public final ByteString reserved_buf;

  /**
   * 服务端使用，客户端忽略
   */
  @ProtoField(tag = 2, type = INT32)
  public final Integer match_result;

  /**
   * 1:ok 2:fail
   */
  @ProtoField(tag = 3)
  public final RouteInfo route_info;

  public MultiMatchRsp(ByteString reserved_buf, Integer match_result, RouteInfo route_info) {
    this.reserved_buf = reserved_buf;
    this.match_result = match_result;
    this.route_info = route_info;
  }

  private MultiMatchRsp(Builder builder) {
    this(builder.reserved_buf, builder.match_result, builder.route_info);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof MultiMatchRsp)) return false;
    MultiMatchRsp o = (MultiMatchRsp) other;
    return equals(reserved_buf, o.reserved_buf)
        && equals(match_result, o.match_result)
        && equals(route_info, o.route_info);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = reserved_buf != null ? reserved_buf.hashCode() : 0;
      result = result * 37 + (match_result != null ? match_result.hashCode() : 0);
      result = result * 37 + (route_info != null ? route_info.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<MultiMatchRsp> {

    public ByteString reserved_buf;
    public Integer match_result;
    public RouteInfo route_info;

    public Builder() {
    }

    public Builder(MultiMatchRsp message) {
      super(message);
      if (message == null) return;
      this.reserved_buf = message.reserved_buf;
      this.match_result = message.match_result;
      this.route_info = message.route_info;
    }

    public Builder reserved_buf(ByteString reserved_buf) {
      this.reserved_buf = reserved_buf;
      return this;
    }

    /**
     * 服务端使用，客户端忽略
     */
    public Builder match_result(Integer match_result) {
      this.match_result = match_result;
      return this;
    }

    /**
     * 1:ok 2:fail
     */
    public Builder route_info(RouteInfo route_info) {
      this.route_info = route_info;
      return this;
    }

    @Override
    public MultiMatchRsp build() {
      return new MultiMatchRsp(this);
    }
  }
}
