// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\match.proto
package com.wesocial.apollo.protocol.protobuf.match;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.INT32;
import static com.squareup.wire.Message.Datatype.INT64;
import static com.squareup.wire.Message.Datatype.UINT64;

public final class PlayerOnlineInfo extends Message {
  private static final long serialVersionUID = 0L;

  public static final Long DEFAULT_INNER_ID = 0L;
  public static final Integer DEFAULT_GAME_ID = 0;
  public static final Integer DEFAULT_GAMESVR_ID = 0;
  public static final Integer DEFAULT_TABLE_ID = 0;
  public static final Long DEFAULT_TABLE_SEQ = 0L;
  public static final Integer DEFAULT_GAME_STATUS = 0;
  public static final Integer DEFAULT_USER_STATUS = 0;
  public static final Integer DEFAULT_CREATE_TIMESTAMP = 0;

  @ProtoField(tag = 1, type = UINT64)
  public final Long inner_id;

  /**
   * 用户id
   */
  @ProtoField(tag = 2, type = INT32)
  public final Integer game_id;

  /**
   * 游戏id
   */
  @ProtoField(tag = 3, type = INT32)
  public final Integer gamesvr_id;

  /**
   * gamesvr id
   */
  @ProtoField(tag = 4, type = INT32)
  public final Integer table_id;

  /**
   * 牌桌id
   */
  @ProtoField(tag = 5, type = INT64)
  public final Long table_seq;

  /**
   * 牌桌seq
   */
  @ProtoField(tag = 6, type = INT32)
  public final Integer game_status;

  /**
   * 牌局状态 1：游戏进行中 2：游戏已结束
   */
  @ProtoField(tag = 7, type = INT32)
  public final Integer user_status;

  /**
   * 用户在牌局中的状态（1：用户在玩 2：用户游戏结束 3：用户强制退出 4：用户匹配中 5：用户初始化状态）
   */
  @ProtoField(tag = 8, type = INT32)
  public final Integer create_timestamp;

  public PlayerOnlineInfo(Long inner_id, Integer game_id, Integer gamesvr_id, Integer table_id, Long table_seq, Integer game_status, Integer user_status, Integer create_timestamp) {
    this.inner_id = inner_id;
    this.game_id = game_id;
    this.gamesvr_id = gamesvr_id;
    this.table_id = table_id;
    this.table_seq = table_seq;
    this.game_status = game_status;
    this.user_status = user_status;
    this.create_timestamp = create_timestamp;
  }

  private PlayerOnlineInfo(Builder builder) {
    this(builder.inner_id, builder.game_id, builder.gamesvr_id, builder.table_id, builder.table_seq, builder.game_status, builder.user_status, builder.create_timestamp);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof PlayerOnlineInfo)) return false;
    PlayerOnlineInfo o = (PlayerOnlineInfo) other;
    return equals(inner_id, o.inner_id)
        && equals(game_id, o.game_id)
        && equals(gamesvr_id, o.gamesvr_id)
        && equals(table_id, o.table_id)
        && equals(table_seq, o.table_seq)
        && equals(game_status, o.game_status)
        && equals(user_status, o.user_status)
        && equals(create_timestamp, o.create_timestamp);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = inner_id != null ? inner_id.hashCode() : 0;
      result = result * 37 + (game_id != null ? game_id.hashCode() : 0);
      result = result * 37 + (gamesvr_id != null ? gamesvr_id.hashCode() : 0);
      result = result * 37 + (table_id != null ? table_id.hashCode() : 0);
      result = result * 37 + (table_seq != null ? table_seq.hashCode() : 0);
      result = result * 37 + (game_status != null ? game_status.hashCode() : 0);
      result = result * 37 + (user_status != null ? user_status.hashCode() : 0);
      result = result * 37 + (create_timestamp != null ? create_timestamp.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<PlayerOnlineInfo> {

    public Long inner_id;
    public Integer game_id;
    public Integer gamesvr_id;
    public Integer table_id;
    public Long table_seq;
    public Integer game_status;
    public Integer user_status;
    public Integer create_timestamp;

    public Builder() {
    }

    public Builder(PlayerOnlineInfo message) {
      super(message);
      if (message == null) return;
      this.inner_id = message.inner_id;
      this.game_id = message.game_id;
      this.gamesvr_id = message.gamesvr_id;
      this.table_id = message.table_id;
      this.table_seq = message.table_seq;
      this.game_status = message.game_status;
      this.user_status = message.user_status;
      this.create_timestamp = message.create_timestamp;
    }

    public Builder inner_id(Long inner_id) {
      this.inner_id = inner_id;
      return this;
    }

    /**
     * 用户id
     */
    public Builder game_id(Integer game_id) {
      this.game_id = game_id;
      return this;
    }

    /**
     * 游戏id
     */
    public Builder gamesvr_id(Integer gamesvr_id) {
      this.gamesvr_id = gamesvr_id;
      return this;
    }

    /**
     * gamesvr id
     */
    public Builder table_id(Integer table_id) {
      this.table_id = table_id;
      return this;
    }

    /**
     * 牌桌id
     */
    public Builder table_seq(Long table_seq) {
      this.table_seq = table_seq;
      return this;
    }

    /**
     * 牌桌seq
     */
    public Builder game_status(Integer game_status) {
      this.game_status = game_status;
      return this;
    }

    /**
     * 牌局状态 1：游戏进行中 2：游戏已结束
     */
    public Builder user_status(Integer user_status) {
      this.user_status = user_status;
      return this;
    }

    /**
     * 用户在牌局中的状态（1：用户在玩 2：用户游戏结束 3：用户强制退出 4：用户匹配中 5：用户初始化状态）
     */
    public Builder create_timestamp(Integer create_timestamp) {
      this.create_timestamp = create_timestamp;
      return this;
    }

    @Override
    public PlayerOnlineInfo build() {
      return new PlayerOnlineInfo(this);
    }
  }
}
