// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\match.proto
package com.wesocial.apollo.protocol.protobuf.match;

import com.squareup.wire.ProtoEnum;

public enum TableStatus
    implements ProtoEnum {
  kTableStatusBetOn(1),
  /**
   * 桌子正在下注状态
   */
  kTableStatusPlaying(2),
  /**
   * 游戏中
   */
  kTableStatusIdle(3);

  private final int value;

  private TableStatus(int value) {
    this.value = value;
  }

  @Override
  public int getValue() {
    return value;
  }
}
