// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\match.proto
package com.wesocial.apollo.protocol.protobuf.match;

import com.squareup.wire.ProtoEnum;

public enum Table_UserStatus
    implements ProtoEnum {
  kUserOnTable(1),
  /**
   * 玩家处于牌桌
   */
  kUserExitTable(2);

  private final int value;

  private Table_UserStatus(int value) {
    this.value = value;
  }

  @Override
  public int getValue() {
    return value;
  }
}
