// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\match.proto
package com.wesocial.apollo.protocol.protobuf.match;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;
import com.wesocial.apollo.protocol.protobuf.game.RouteInfo;

import static com.squareup.wire.Message.Datatype.INT32;
import static com.squareup.wire.Message.Datatype.UINT64;

public final class UserOnlineInfo extends Message {
  private static final long serialVersionUID = 0L;

  public static final Long DEFAULT_INNER_ID = 0L;
  public static final Integer DEFAULT_USER_STATUS = 0;
  public static final Integer DEFAULT_CREATE_TIMESTAMP = 0;

  @ProtoField(tag = 1, type = UINT64)
  public final Long inner_id;

  /**
   * 用户id
   */
  @ProtoField(tag = 2)
  public final RouteInfo route_info;

  /**
   * 路由信息
   */
  @ProtoField(tag = 3, type = INT32)
  public final Integer user_status;

  /**
   * 用户状态
   */
  @ProtoField(tag = 4, type = INT32)
  public final Integer create_timestamp;

  public UserOnlineInfo(Long inner_id, RouteInfo route_info, Integer user_status, Integer create_timestamp) {
    this.inner_id = inner_id;
    this.route_info = route_info;
    this.user_status = user_status;
    this.create_timestamp = create_timestamp;
  }

  private UserOnlineInfo(Builder builder) {
    this(builder.inner_id, builder.route_info, builder.user_status, builder.create_timestamp);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof UserOnlineInfo)) return false;
    UserOnlineInfo o = (UserOnlineInfo) other;
    return equals(inner_id, o.inner_id)
        && equals(route_info, o.route_info)
        && equals(user_status, o.user_status)
        && equals(create_timestamp, o.create_timestamp);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = inner_id != null ? inner_id.hashCode() : 0;
      result = result * 37 + (route_info != null ? route_info.hashCode() : 0);
      result = result * 37 + (user_status != null ? user_status.hashCode() : 0);
      result = result * 37 + (create_timestamp != null ? create_timestamp.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<UserOnlineInfo> {

    public Long inner_id;
    public RouteInfo route_info;
    public Integer user_status;
    public Integer create_timestamp;

    public Builder() {
    }

    public Builder(UserOnlineInfo message) {
      super(message);
      if (message == null) return;
      this.inner_id = message.inner_id;
      this.route_info = message.route_info;
      this.user_status = message.user_status;
      this.create_timestamp = message.create_timestamp;
    }

    public Builder inner_id(Long inner_id) {
      this.inner_id = inner_id;
      return this;
    }

    /**
     * 用户id
     */
    public Builder route_info(RouteInfo route_info) {
      this.route_info = route_info;
      return this;
    }

    /**
     * 路由信息
     */
    public Builder user_status(Integer user_status) {
      this.user_status = user_status;
      return this;
    }

    /**
     * 用户状态
     */
    public Builder create_timestamp(Integer create_timestamp) {
      this.create_timestamp = create_timestamp;
      return this;
    }

    @Override
    public UserOnlineInfo build() {
      return new UserOnlineInfo(this);
    }
  }
}
