// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\match.proto
package com.wesocial.apollo.protocol.protobuf.match;

import com.squareup.wire.ProtoEnum;

public enum UserStatus
    implements ProtoEnum {
  kUserStatusPredistribution(1),
  /**
   * 玩家处于预分配状态
   */
  kUserStatusIdle(2),
  /**
   * 玩家处于空闲状态
   */
  kUserStatusPlaying(3),
  /**
   * 游戏中
   */
  kUserStatusMatching(4);

  private final int value;

  private UserStatus(int value) {
    this.value = value;
  }

  @Override
  public int getValue() {
    return value;
  }
}
