// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\profile.proto
package com.wesocial.apollo.protocol.protobuf.profile;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;
import java.util.Collections;
import java.util.List;
import okio.ByteString;

import static com.squareup.wire.Message.Datatype.BYTES;
import static com.squareup.wire.Message.Datatype.INT32;
import static com.squareup.wire.Message.Label.REPEATED;

/**
 * IV. 批量拉取用户基础信息
 * CMD为BATCH_GET_USER_INFO（202），请求结构为BatchGetUserInfoReq，回应结构为BatchGetUserInfoRsp
 */
public final class BatchGetUserInfoReq extends Message {
  private static final long serialVersionUID = 0L;

  public static final ByteString DEFAULT_RESERVED_BUF = ByteString.EMPTY;
  public static final List<FriendIdInfo> DEFAULT_FRIEND_ID_INFO = Collections.emptyList();
  public static final Integer DEFAULT_REQ_TYPE = 0;

  @ProtoField(tag = 1, type = BYTES)
  public final ByteString reserved_buf;

  /**
   * 服务端使用，客户端忽略
   */
  @ProtoField(tag = 2, label = REPEATED, messageType = FriendIdInfo.class)
  public final List<FriendIdInfo> friend_id_info;

  @ProtoField(tag = 3, type = INT32)
  public final Integer req_type;

  public BatchGetUserInfoReq(ByteString reserved_buf, List<FriendIdInfo> friend_id_info, Integer req_type) {
    this.reserved_buf = reserved_buf;
    this.friend_id_info = immutableCopyOf(friend_id_info);
    this.req_type = req_type;
  }

  private BatchGetUserInfoReq(Builder builder) {
    this(builder.reserved_buf, builder.friend_id_info, builder.req_type);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof BatchGetUserInfoReq)) return false;
    BatchGetUserInfoReq o = (BatchGetUserInfoReq) other;
    return equals(reserved_buf, o.reserved_buf)
        && equals(friend_id_info, o.friend_id_info)
        && equals(req_type, o.req_type);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = reserved_buf != null ? reserved_buf.hashCode() : 0;
      result = result * 37 + (friend_id_info != null ? friend_id_info.hashCode() : 1);
      result = result * 37 + (req_type != null ? req_type.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<BatchGetUserInfoReq> {

    public ByteString reserved_buf;
    public List<FriendIdInfo> friend_id_info;
    public Integer req_type;

    public Builder() {
    }

    public Builder(BatchGetUserInfoReq message) {
      super(message);
      if (message == null) return;
      this.reserved_buf = message.reserved_buf;
      this.friend_id_info = copyOf(message.friend_id_info);
      this.req_type = message.req_type;
    }

    public Builder reserved_buf(ByteString reserved_buf) {
      this.reserved_buf = reserved_buf;
      return this;
    }

    /**
     * 服务端使用，客户端忽略
     */
    public Builder friend_id_info(List<FriendIdInfo> friend_id_info) {
      this.friend_id_info = checkForNulls(friend_id_info);
      return this;
    }

    public Builder req_type(Integer req_type) {
      this.req_type = req_type;
      return this;
    }

    @Override
    public BatchGetUserInfoReq build() {
      return new BatchGetUserInfoReq(this);
    }
  }
}
