// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\profile.proto
package com.wesocial.apollo.protocol.protobuf.profile;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.INT32;
import static com.squareup.wire.Message.Datatype.STRING;

/**
 * 用户扩展信息
 */
public final class ExtraUserInfo extends Message {
  private static final long serialVersionUID = 0L;

  public static final String DEFAULT_INTRO = "";
  public static final Integer DEFAULT_ARTICLE_NUM = 0;
  public static final Integer DEFAULT_ANSWER_NUM = 0;
  public static final Integer DEFAULT_COMPLETE_DEGREE = 0;
  public static final Integer DEFAULT_RECEIVED_PRESENT_NUM = 0;

  @ProtoField(tag = 1, type = STRING)
  public final String intro;

  /**
   * 用户记录的"我想用"信息
   */
  @ProtoField(tag = 2, type = INT32)
  public final Integer article_num;

  /**
   * 用户发表的文章数量
   */
  @ProtoField(tag = 3, type = INT32)
  public final Integer answer_num;

  /**
   * 用户已答题数量
   */
  @ProtoField(tag = 4, type = INT32)
  public final Integer complete_degree;

  /**
   * 资料完善程度 （0-100）
   */
  @ProtoField(tag = 5, type = INT32)
  public final Integer received_present_num;

  public ExtraUserInfo(String intro, Integer article_num, Integer answer_num, Integer complete_degree, Integer received_present_num) {
    this.intro = intro;
    this.article_num = article_num;
    this.answer_num = answer_num;
    this.complete_degree = complete_degree;
    this.received_present_num = received_present_num;
  }

  private ExtraUserInfo(Builder builder) {
    this(builder.intro, builder.article_num, builder.answer_num, builder.complete_degree, builder.received_present_num);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof ExtraUserInfo)) return false;
    ExtraUserInfo o = (ExtraUserInfo) other;
    return equals(intro, o.intro)
        && equals(article_num, o.article_num)
        && equals(answer_num, o.answer_num)
        && equals(complete_degree, o.complete_degree)
        && equals(received_present_num, o.received_present_num);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = intro != null ? intro.hashCode() : 0;
      result = result * 37 + (article_num != null ? article_num.hashCode() : 0);
      result = result * 37 + (answer_num != null ? answer_num.hashCode() : 0);
      result = result * 37 + (complete_degree != null ? complete_degree.hashCode() : 0);
      result = result * 37 + (received_present_num != null ? received_present_num.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<ExtraUserInfo> {

    public String intro;
    public Integer article_num;
    public Integer answer_num;
    public Integer complete_degree;
    public Integer received_present_num;

    public Builder() {
    }

    public Builder(ExtraUserInfo message) {
      super(message);
      if (message == null) return;
      this.intro = message.intro;
      this.article_num = message.article_num;
      this.answer_num = message.answer_num;
      this.complete_degree = message.complete_degree;
      this.received_present_num = message.received_present_num;
    }

    public Builder intro(String intro) {
      this.intro = intro;
      return this;
    }

    /**
     * 用户记录的"我想用"信息
     */
    public Builder article_num(Integer article_num) {
      this.article_num = article_num;
      return this;
    }

    /**
     * 用户发表的文章数量
     */
    public Builder answer_num(Integer answer_num) {
      this.answer_num = answer_num;
      return this;
    }

    /**
     * 用户已答题数量
     */
    public Builder complete_degree(Integer complete_degree) {
      this.complete_degree = complete_degree;
      return this;
    }

    /**
     * 资料完善程度 （0-100）
     */
    public Builder received_present_num(Integer received_present_num) {
      this.received_present_num = received_present_num;
      return this;
    }

    @Override
    public ExtraUserInfo build() {
      return new ExtraUserInfo(this);
    }
  }
}
