// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\profile.proto
package com.wesocial.apollo.protocol.protobuf.profile;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.UINT32;
import static com.squareup.wire.Message.Datatype.UINT64;

/**
 * 用于批量获取好友信息的结构
 */
public final class FriendIdInfo extends Message {
  private static final long serialVersionUID = 0L;

  public static final Long DEFAULT_INNER_ID = 0L;
  public static final Integer DEFAULT_BASE_VERSION = 0;

  @ProtoField(tag = 1, type = UINT64)
  public final Long inner_id;

  @ProtoField(tag = 2, type = UINT32)
  public final Integer base_version;

  public FriendIdInfo(Long inner_id, Integer base_version) {
    this.inner_id = inner_id;
    this.base_version = base_version;
  }

  private FriendIdInfo(Builder builder) {
    this(builder.inner_id, builder.base_version);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof FriendIdInfo)) return false;
    FriendIdInfo o = (FriendIdInfo) other;
    return equals(inner_id, o.inner_id)
        && equals(base_version, o.base_version);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = inner_id != null ? inner_id.hashCode() : 0;
      result = result * 37 + (base_version != null ? base_version.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<FriendIdInfo> {

    public Long inner_id;
    public Integer base_version;

    public Builder() {
    }

    public Builder(FriendIdInfo message) {
      super(message);
      if (message == null) return;
      this.inner_id = message.inner_id;
      this.base_version = message.base_version;
    }

    public Builder inner_id(Long inner_id) {
      this.inner_id = inner_id;
      return this;
    }

    public Builder base_version(Integer base_version) {
      this.base_version = base_version;
      return this;
    }

    @Override
    public FriendIdInfo build() {
      return new FriendIdInfo(this);
    }
  }
}
