// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\profile.proto
package com.wesocial.apollo.protocol.protobuf.profile;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;
import okio.ByteString;

import static com.squareup.wire.Message.Datatype.BYTES;
import static com.squareup.wire.Message.Datatype.INT32;

/**
 * XVII. 获取所有在有效期内的礼包活动列表
 * CMD为GET_GIFT_ACTIVITY（301）
 */
public final class GetGiftActivityReq extends Message {
  private static final long serialVersionUID = 0L;

  public static final ByteString DEFAULT_RESERVED_BUF = ByteString.EMPTY;
  public static final Integer DEFAULT_TIME_FILTER = 0;
  public static final Integer DEFAULT_ACTIVITY_ID = 0;

  @ProtoField(tag = 1, type = BYTES)
  public final ByteString reserved_buf;

  /**
   * 服务端使用，客户端忽略
   */
  @ProtoField(tag = 2, type = INT32)
  public final Integer time_filter;

  /**
   * 1：获取有效期内的活动 2：获取已失效的活动 3：获取所有活动
   */
  @ProtoField(tag = 3, type = INT32)
  public final Integer activity_id;

  public GetGiftActivityReq(ByteString reserved_buf, Integer time_filter, Integer activity_id) {
    this.reserved_buf = reserved_buf;
    this.time_filter = time_filter;
    this.activity_id = activity_id;
  }

  private GetGiftActivityReq(Builder builder) {
    this(builder.reserved_buf, builder.time_filter, builder.activity_id);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof GetGiftActivityReq)) return false;
    GetGiftActivityReq o = (GetGiftActivityReq) other;
    return equals(reserved_buf, o.reserved_buf)
        && equals(time_filter, o.time_filter)
        && equals(activity_id, o.activity_id);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = reserved_buf != null ? reserved_buf.hashCode() : 0;
      result = result * 37 + (time_filter != null ? time_filter.hashCode() : 0);
      result = result * 37 + (activity_id != null ? activity_id.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<GetGiftActivityReq> {

    public ByteString reserved_buf;
    public Integer time_filter;
    public Integer activity_id;

    public Builder() {
    }

    public Builder(GetGiftActivityReq message) {
      super(message);
      if (message == null) return;
      this.reserved_buf = message.reserved_buf;
      this.time_filter = message.time_filter;
      this.activity_id = message.activity_id;
    }

    public Builder reserved_buf(ByteString reserved_buf) {
      this.reserved_buf = reserved_buf;
      return this;
    }

    /**
     * 服务端使用，客户端忽略
     */
    public Builder time_filter(Integer time_filter) {
      this.time_filter = time_filter;
      return this;
    }

    /**
     * 1：获取有效期内的活动 2：获取已失效的活动 3：获取所有活动
     */
    public Builder activity_id(Integer activity_id) {
      this.activity_id = activity_id;
      return this;
    }

    @Override
    public GetGiftActivityReq build() {
      return new GetGiftActivityReq(this);
    }
  }
}
