// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\profile.proto
package com.wesocial.apollo.protocol.protobuf.profile;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;
import okio.ByteString;

import static com.squareup.wire.Message.Datatype.BYTES;

/**
 * XIII. 查看自己的标签
 * CMD为GET_OWNER_PROFILE_TAG_V2（107）
 */
public final class GetOwnerProfileTagV2Req extends Message {
  private static final long serialVersionUID = 0L;

  public static final ByteString DEFAULT_RESERVED_BUF = ByteString.EMPTY;

  @ProtoField(tag = 1, type = BYTES)
  public final ByteString reserved_buf;

  public GetOwnerProfileTagV2Req(ByteString reserved_buf) {
    this.reserved_buf = reserved_buf;
  }

  private GetOwnerProfileTagV2Req(Builder builder) {
    this(builder.reserved_buf);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof GetOwnerProfileTagV2Req)) return false;
    return equals(reserved_buf, ((GetOwnerProfileTagV2Req) other).reserved_buf);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    return result != 0 ? result : (hashCode = reserved_buf != null ? reserved_buf.hashCode() : 0);
  }

  public static final class Builder extends Message.Builder<GetOwnerProfileTagV2Req> {

    public ByteString reserved_buf;

    public Builder() {
    }

    public Builder(GetOwnerProfileTagV2Req message) {
      super(message);
      if (message == null) return;
      this.reserved_buf = message.reserved_buf;
    }

    public Builder reserved_buf(ByteString reserved_buf) {
      this.reserved_buf = reserved_buf;
      return this;
    }

    @Override
    public GetOwnerProfileTagV2Req build() {
      return new GetOwnerProfileTagV2Req(this);
    }
  }
}
