// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\profile.proto
package com.wesocial.apollo.protocol.protobuf.profile;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;
import java.util.Collections;
import java.util.List;
import okio.ByteString;

import static com.squareup.wire.Message.Datatype.BYTES;
import static com.squareup.wire.Message.Datatype.INT32;
import static com.squareup.wire.Message.Label.REPEATED;

public final class GetRecentVisitorRsp extends Message {
  private static final long serialVersionUID = 0L;

  public static final ByteString DEFAULT_RESERVED_BUF = ByteString.EMPTY;
  public static final List<VisitorInfo> DEFAULT_VISITOR_INFO_LIST = Collections.emptyList();
  public static final Integer DEFAULT_TOTAL_VISITOR_NUM = 0;
  public static final Integer DEFAULT_TODAY_VISITOR_NUM = 0;

  @ProtoField(tag = 1, type = BYTES)
  public final ByteString reserved_buf;

  /**
   * 服务端使用，客户端忽略
   */
  @ProtoField(tag = 2, label = REPEATED, messageType = VisitorInfo.class)
  public final List<VisitorInfo> visitor_info_list;

  /**
   * 用户inner_id列表
   */
  @ProtoField(tag = 3, type = INT32)
  public final Integer total_visitor_num;

  /**
   * 历史访问总用户
   */
  @ProtoField(tag = 4, type = INT32)
  public final Integer today_visitor_num;

  public GetRecentVisitorRsp(ByteString reserved_buf, List<VisitorInfo> visitor_info_list, Integer total_visitor_num, Integer today_visitor_num) {
    this.reserved_buf = reserved_buf;
    this.visitor_info_list = immutableCopyOf(visitor_info_list);
    this.total_visitor_num = total_visitor_num;
    this.today_visitor_num = today_visitor_num;
  }

  private GetRecentVisitorRsp(Builder builder) {
    this(builder.reserved_buf, builder.visitor_info_list, builder.total_visitor_num, builder.today_visitor_num);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof GetRecentVisitorRsp)) return false;
    GetRecentVisitorRsp o = (GetRecentVisitorRsp) other;
    return equals(reserved_buf, o.reserved_buf)
        && equals(visitor_info_list, o.visitor_info_list)
        && equals(total_visitor_num, o.total_visitor_num)
        && equals(today_visitor_num, o.today_visitor_num);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = reserved_buf != null ? reserved_buf.hashCode() : 0;
      result = result * 37 + (visitor_info_list != null ? visitor_info_list.hashCode() : 1);
      result = result * 37 + (total_visitor_num != null ? total_visitor_num.hashCode() : 0);
      result = result * 37 + (today_visitor_num != null ? today_visitor_num.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<GetRecentVisitorRsp> {

    public ByteString reserved_buf;
    public List<VisitorInfo> visitor_info_list;
    public Integer total_visitor_num;
    public Integer today_visitor_num;

    public Builder() {
    }

    public Builder(GetRecentVisitorRsp message) {
      super(message);
      if (message == null) return;
      this.reserved_buf = message.reserved_buf;
      this.visitor_info_list = copyOf(message.visitor_info_list);
      this.total_visitor_num = message.total_visitor_num;
      this.today_visitor_num = message.today_visitor_num;
    }

    public Builder reserved_buf(ByteString reserved_buf) {
      this.reserved_buf = reserved_buf;
      return this;
    }

    /**
     * 服务端使用，客户端忽略
     */
    public Builder visitor_info_list(List<VisitorInfo> visitor_info_list) {
      this.visitor_info_list = checkForNulls(visitor_info_list);
      return this;
    }

    /**
     * 用户inner_id列表
     */
    public Builder total_visitor_num(Integer total_visitor_num) {
      this.total_visitor_num = total_visitor_num;
      return this;
    }

    /**
     * 历史访问总用户
     */
    public Builder today_visitor_num(Integer today_visitor_num) {
      this.today_visitor_num = today_visitor_num;
      return this;
    }

    @Override
    public GetRecentVisitorRsp build() {
      return new GetRecentVisitorRsp(this);
    }
  }
}
