// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\profile.proto
package com.wesocial.apollo.protocol.protobuf.profile;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;
import okio.ByteString;

import static com.squareup.wire.Message.Datatype.BYTES;
import static com.squareup.wire.Message.Datatype.UINT32;

public final class GetScreenShotNumRsp extends Message {
  private static final long serialVersionUID = 0L;

  public static final ByteString DEFAULT_RESERVED_BUF = ByteString.EMPTY;
  public static final Integer DEFAULT_NUM = 0;

  @ProtoField(tag = 1, type = BYTES)
  public final ByteString reserved_buf;

  /**
   * 服务端使用，客户端忽略
   */
  @ProtoField(tag = 2, type = UINT32)
  public final Integer num;

  public GetScreenShotNumRsp(ByteString reserved_buf, Integer num) {
    this.reserved_buf = reserved_buf;
    this.num = num;
  }

  private GetScreenShotNumRsp(Builder builder) {
    this(builder.reserved_buf, builder.num);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof GetScreenShotNumRsp)) return false;
    GetScreenShotNumRsp o = (GetScreenShotNumRsp) other;
    return equals(reserved_buf, o.reserved_buf)
        && equals(num, o.num);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = reserved_buf != null ? reserved_buf.hashCode() : 0;
      result = result * 37 + (num != null ? num.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<GetScreenShotNumRsp> {

    public ByteString reserved_buf;
    public Integer num;

    public Builder() {
    }

    public Builder(GetScreenShotNumRsp message) {
      super(message);
      if (message == null) return;
      this.reserved_buf = message.reserved_buf;
      this.num = message.num;
    }

    public Builder reserved_buf(ByteString reserved_buf) {
      this.reserved_buf = reserved_buf;
      return this;
    }

    /**
     * 服务端使用，客户端忽略
     */
    public Builder num(Integer num) {
      this.num = num;
      return this;
    }

    @Override
    public GetScreenShotNumRsp build() {
      return new GetScreenShotNumRsp(this);
    }
  }
}
