// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\profile.proto
package com.wesocial.apollo.protocol.protobuf.profile;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;
import okio.ByteString;

import static com.squareup.wire.Message.Datatype.BYTES;
import static com.squareup.wire.Message.Datatype.UINT64;

/**
 * 获取用户截屏次数
 */
public final class GetScreenShotNumReq extends Message {
  private static final long serialVersionUID = 0L;

  public static final ByteString DEFAULT_RESERVED_BUF = ByteString.EMPTY;
  public static final Long DEFAULT_TO_INNER_ID = 0L;

  @ProtoField(tag = 1, type = BYTES)
  public final ByteString reserved_buf;

  /**
   * 服务端使用，客户端忽略
   */
  @ProtoField(tag = 2, type = UINT64)
  public final Long to_inner_id;

  public GetScreenShotNumReq(ByteString reserved_buf, Long to_inner_id) {
    this.reserved_buf = reserved_buf;
    this.to_inner_id = to_inner_id;
  }

  private GetScreenShotNumReq(Builder builder) {
    this(builder.reserved_buf, builder.to_inner_id);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof GetScreenShotNumReq)) return false;
    GetScreenShotNumReq o = (GetScreenShotNumReq) other;
    return equals(reserved_buf, o.reserved_buf)
        && equals(to_inner_id, o.to_inner_id);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = reserved_buf != null ? reserved_buf.hashCode() : 0;
      result = result * 37 + (to_inner_id != null ? to_inner_id.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<GetScreenShotNumReq> {

    public ByteString reserved_buf;
    public Long to_inner_id;

    public Builder() {
    }

    public Builder(GetScreenShotNumReq message) {
      super(message);
      if (message == null) return;
      this.reserved_buf = message.reserved_buf;
      this.to_inner_id = message.to_inner_id;
    }

    public Builder reserved_buf(ByteString reserved_buf) {
      this.reserved_buf = reserved_buf;
      return this;
    }

    /**
     * 服务端使用，客户端忽略
     */
    public Builder to_inner_id(Long to_inner_id) {
      this.to_inner_id = to_inner_id;
      return this;
    }

    @Override
    public GetScreenShotNumReq build() {
      return new GetScreenShotNumReq(this);
    }
  }
}
