// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\profile.proto
package com.wesocial.apollo.protocol.protobuf.profile;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;
import okio.ByteString;

import static com.squareup.wire.Message.Datatype.BYTES;
import static com.squareup.wire.Message.Datatype.UINT32;
import static com.squareup.wire.Message.Datatype.UINT64;

/**
 * 获取排行榜的汇总， 包括女神和富豪的日榜和周榜单
 */
public final class GetTopRankUserAllReq extends Message {
  private static final long serialVersionUID = 0L;

  public static final ByteString DEFAULT_RESERVED_BUF = ByteString.EMPTY;
  public static final Long DEFAULT_VERSION = 0L;
  public static final Integer DEFAULT_ITEM_NUM = 0;

  @ProtoField(tag = 1, type = BYTES)
  public final ByteString reserved_buf;

  /**
   * 服务端使用，客户端忽略
   */
  @ProtoField(tag = 2, type = UINT64)
  public final Long version;

  /**
   * 版本号， 默认填0,
   */
  @ProtoField(tag = 3, type = UINT32)
  public final Integer item_num;

  public GetTopRankUserAllReq(ByteString reserved_buf, Long version, Integer item_num) {
    this.reserved_buf = reserved_buf;
    this.version = version;
    this.item_num = item_num;
  }

  private GetTopRankUserAllReq(Builder builder) {
    this(builder.reserved_buf, builder.version, builder.item_num);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof GetTopRankUserAllReq)) return false;
    GetTopRankUserAllReq o = (GetTopRankUserAllReq) other;
    return equals(reserved_buf, o.reserved_buf)
        && equals(version, o.version)
        && equals(item_num, o.item_num);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = reserved_buf != null ? reserved_buf.hashCode() : 0;
      result = result * 37 + (version != null ? version.hashCode() : 0);
      result = result * 37 + (item_num != null ? item_num.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<GetTopRankUserAllReq> {

    public ByteString reserved_buf;
    public Long version;
    public Integer item_num;

    public Builder() {
    }

    public Builder(GetTopRankUserAllReq message) {
      super(message);
      if (message == null) return;
      this.reserved_buf = message.reserved_buf;
      this.version = message.version;
      this.item_num = message.item_num;
    }

    public Builder reserved_buf(ByteString reserved_buf) {
      this.reserved_buf = reserved_buf;
      return this;
    }

    /**
     * 服务端使用，客户端忽略
     */
    public Builder version(Long version) {
      this.version = version;
      return this;
    }

    /**
     * 版本号， 默认填0,
     */
    public Builder item_num(Integer item_num) {
      this.item_num = item_num;
      return this;
    }

    @Override
    public GetTopRankUserAllReq build() {
      return new GetTopRankUserAllReq(this);
    }
  }
}
