// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\profile.proto
package com.wesocial.apollo.protocol.protobuf.profile;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;
import okio.ByteString;

import static com.squareup.wire.Message.Datatype.BYTES;

public final class GetTopRankUserRsp extends Message {
  private static final long serialVersionUID = 0L;

  public static final ByteString DEFAULT_RESERVED_BUF = ByteString.EMPTY;

  @ProtoField(tag = 1, type = BYTES)
  public final ByteString reserved_buf;

  /**
   * 服务端使用，客户端忽略
   */
  @ProtoField(tag = 2)
  public final RankUserList list;

  public GetTopRankUserRsp(ByteString reserved_buf, RankUserList list) {
    this.reserved_buf = reserved_buf;
    this.list = list;
  }

  private GetTopRankUserRsp(Builder builder) {
    this(builder.reserved_buf, builder.list);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof GetTopRankUserRsp)) return false;
    GetTopRankUserRsp o = (GetTopRankUserRsp) other;
    return equals(reserved_buf, o.reserved_buf)
        && equals(list, o.list);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = reserved_buf != null ? reserved_buf.hashCode() : 0;
      result = result * 37 + (list != null ? list.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<GetTopRankUserRsp> {

    public ByteString reserved_buf;
    public RankUserList list;

    public Builder() {
    }

    public Builder(GetTopRankUserRsp message) {
      super(message);
      if (message == null) return;
      this.reserved_buf = message.reserved_buf;
      this.list = message.list;
    }

    public Builder reserved_buf(ByteString reserved_buf) {
      this.reserved_buf = reserved_buf;
      return this;
    }

    /**
     * 服务端使用，客户端忽略
     */
    public Builder list(RankUserList list) {
      this.list = list;
      return this;
    }

    @Override
    public GetTopRankUserRsp build() {
      return new GetTopRankUserRsp(this);
    }
  }
}
