// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\profile.proto
package com.wesocial.apollo.protocol.protobuf.profile;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;
import okio.ByteString;

import static com.squareup.wire.Message.Datatype.BYTES;
import static com.squareup.wire.Message.Datatype.UINT32;

public final class GetTopRankUserAllRsp extends Message {
  private static final long serialVersionUID = 0L;

  public static final ByteString DEFAULT_RESERVED_BUF = ByteString.EMPTY;
  public static final Integer DEFAULT_VERSION = 0;

  @ProtoField(tag = 1, type = BYTES)
  public final ByteString reserved_buf;

  /**
   * 服务端使用，客户端忽略
   */
  @ProtoField(tag = 2, type = UINT32)
  public final Integer version;

  /**
   * 所有榜单的最大版本号
   */
  @ProtoField(tag = 3)
  public final RankUserList daily_goddess;

  /**
   * 女神日榜单
   */
  @ProtoField(tag = 4)
  public final RankUserList week_goddess;

  /**
   * 女神周榜单
   */
  @ProtoField(tag = 5)
  public final RankUserList daily_nabob;

  /**
   * 土豪日榜单
   */
  @ProtoField(tag = 6)
  public final RankUserList week_nabob;

  public GetTopRankUserAllRsp(ByteString reserved_buf, Integer version, RankUserList daily_goddess, RankUserList week_goddess, RankUserList daily_nabob, RankUserList week_nabob) {
    this.reserved_buf = reserved_buf;
    this.version = version;
    this.daily_goddess = daily_goddess;
    this.week_goddess = week_goddess;
    this.daily_nabob = daily_nabob;
    this.week_nabob = week_nabob;
  }

  private GetTopRankUserAllRsp(Builder builder) {
    this(builder.reserved_buf, builder.version, builder.daily_goddess, builder.week_goddess, builder.daily_nabob, builder.week_nabob);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof GetTopRankUserAllRsp)) return false;
    GetTopRankUserAllRsp o = (GetTopRankUserAllRsp) other;
    return equals(reserved_buf, o.reserved_buf)
        && equals(version, o.version)
        && equals(daily_goddess, o.daily_goddess)
        && equals(week_goddess, o.week_goddess)
        && equals(daily_nabob, o.daily_nabob)
        && equals(week_nabob, o.week_nabob);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = reserved_buf != null ? reserved_buf.hashCode() : 0;
      result = result * 37 + (version != null ? version.hashCode() : 0);
      result = result * 37 + (daily_goddess != null ? daily_goddess.hashCode() : 0);
      result = result * 37 + (week_goddess != null ? week_goddess.hashCode() : 0);
      result = result * 37 + (daily_nabob != null ? daily_nabob.hashCode() : 0);
      result = result * 37 + (week_nabob != null ? week_nabob.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<GetTopRankUserAllRsp> {

    public ByteString reserved_buf;
    public Integer version;
    public RankUserList daily_goddess;
    public RankUserList week_goddess;
    public RankUserList daily_nabob;
    public RankUserList week_nabob;

    public Builder() {
    }

    public Builder(GetTopRankUserAllRsp message) {
      super(message);
      if (message == null) return;
      this.reserved_buf = message.reserved_buf;
      this.version = message.version;
      this.daily_goddess = message.daily_goddess;
      this.week_goddess = message.week_goddess;
      this.daily_nabob = message.daily_nabob;
      this.week_nabob = message.week_nabob;
    }

    public Builder reserved_buf(ByteString reserved_buf) {
      this.reserved_buf = reserved_buf;
      return this;
    }

    /**
     * 服务端使用，客户端忽略
     */
    public Builder version(Integer version) {
      this.version = version;
      return this;
    }

    /**
     * 所有榜单的最大版本号
     */
    public Builder daily_goddess(RankUserList daily_goddess) {
      this.daily_goddess = daily_goddess;
      return this;
    }

    /**
     * 女神日榜单
     */
    public Builder week_goddess(RankUserList week_goddess) {
      this.week_goddess = week_goddess;
      return this;
    }

    /**
     * 女神周榜单
     */
    public Builder daily_nabob(RankUserList daily_nabob) {
      this.daily_nabob = daily_nabob;
      return this;
    }

    /**
     * 土豪日榜单
     */
    public Builder week_nabob(RankUserList week_nabob) {
      this.week_nabob = week_nabob;
      return this;
    }

    @Override
    public GetTopRankUserAllRsp build() {
      return new GetTopRankUserAllRsp(this);
    }
  }
}
