// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\profile.proto
package com.wesocial.apollo.protocol.protobuf.profile;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;
import okio.ByteString;

import static com.squareup.wire.Message.Datatype.BYTES;
import static com.squareup.wire.Message.Datatype.UINT32;
import static com.squareup.wire.Message.Datatype.UINT64;

/**
 * III. 拉取个人详细信息
 * CMD为GET_USER_INFO（201）
 * 获取用户自己或者他人的详细信息
 */
public final class GetUserInfoReq extends Message {
  private static final long serialVersionUID = 0L;

  public static final ByteString DEFAULT_RESERVED_BUF = ByteString.EMPTY;
  public static final Long DEFAULT_VISIT_INNER_ID = 0L;
  public static final Integer DEFAULT_BASE_VERSION = 0;
  public static final Integer DEFAULT_EXTRA_VERSION = 0;
  public static final Integer DEFAULT_PIC_VERSION = 0;

  @ProtoField(tag = 1, type = BYTES)
  public final ByteString reserved_buf;

  /**
   * 服务端使用，客户端忽略
   */
  @ProtoField(tag = 2, type = UINT64)
  public final Long visit_inner_id;

  /**
   * 被查看用户的inner_id，如果是查看自己的则与inner_id一致
   */
  @ProtoField(tag = 3, type = UINT32)
  public final Integer base_version;

  @ProtoField(tag = 4, type = UINT32)
  public final Integer extra_version;

  @ProtoField(tag = 5, type = UINT32)
  public final Integer pic_version;

  public GetUserInfoReq(ByteString reserved_buf, Long visit_inner_id, Integer base_version, Integer extra_version, Integer pic_version) {
    this.reserved_buf = reserved_buf;
    this.visit_inner_id = visit_inner_id;
    this.base_version = base_version;
    this.extra_version = extra_version;
    this.pic_version = pic_version;
  }

  private GetUserInfoReq(Builder builder) {
    this(builder.reserved_buf, builder.visit_inner_id, builder.base_version, builder.extra_version, builder.pic_version);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof GetUserInfoReq)) return false;
    GetUserInfoReq o = (GetUserInfoReq) other;
    return equals(reserved_buf, o.reserved_buf)
        && equals(visit_inner_id, o.visit_inner_id)
        && equals(base_version, o.base_version)
        && equals(extra_version, o.extra_version)
        && equals(pic_version, o.pic_version);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = reserved_buf != null ? reserved_buf.hashCode() : 0;
      result = result * 37 + (visit_inner_id != null ? visit_inner_id.hashCode() : 0);
      result = result * 37 + (base_version != null ? base_version.hashCode() : 0);
      result = result * 37 + (extra_version != null ? extra_version.hashCode() : 0);
      result = result * 37 + (pic_version != null ? pic_version.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<GetUserInfoReq> {

    public ByteString reserved_buf;
    public Long visit_inner_id;
    public Integer base_version;
    public Integer extra_version;
    public Integer pic_version;

    public Builder() {
    }

    public Builder(GetUserInfoReq message) {
      super(message);
      if (message == null) return;
      this.reserved_buf = message.reserved_buf;
      this.visit_inner_id = message.visit_inner_id;
      this.base_version = message.base_version;
      this.extra_version = message.extra_version;
      this.pic_version = message.pic_version;
    }

    public Builder reserved_buf(ByteString reserved_buf) {
      this.reserved_buf = reserved_buf;
      return this;
    }

    /**
     * 服务端使用，客户端忽略
     */
    public Builder visit_inner_id(Long visit_inner_id) {
      this.visit_inner_id = visit_inner_id;
      return this;
    }

    /**
     * 被查看用户的inner_id，如果是查看自己的则与inner_id一致
     */
    public Builder base_version(Integer base_version) {
      this.base_version = base_version;
      return this;
    }

    public Builder extra_version(Integer extra_version) {
      this.extra_version = extra_version;
      return this;
    }

    public Builder pic_version(Integer pic_version) {
      this.pic_version = pic_version;
      return this;
    }

    @Override
    public GetUserInfoReq build() {
      return new GetUserInfoReq(this);
    }
  }
}
