// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\profile.proto
package com.wesocial.apollo.protocol.protobuf.profile;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;
import okio.ByteString;

import static com.squareup.wire.Message.Datatype.BYTES;
import static com.squareup.wire.Message.Datatype.INT32;

/**
 * GET_USER_TASK_LIST 208
 * 拉取用户任务列表
 */
public final class GetUserTaskListReq extends Message {
  private static final long serialVersionUID = 0L;

  public static final ByteString DEFAULT_RESERVED_BUF = ByteString.EMPTY;
  public static final Integer DEFAULT_REQ_TYPE = 0;

  @ProtoField(tag = 1, type = BYTES)
  public final ByteString reserved_buf;

  /**
   * 服务端使用，客户端忽略
   */
  @ProtoField(tag = 2, type = INT32)
  public final Integer req_type;

  public GetUserTaskListReq(ByteString reserved_buf, Integer req_type) {
    this.reserved_buf = reserved_buf;
    this.req_type = req_type;
  }

  private GetUserTaskListReq(Builder builder) {
    this(builder.reserved_buf, builder.req_type);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof GetUserTaskListReq)) return false;
    GetUserTaskListReq o = (GetUserTaskListReq) other;
    return equals(reserved_buf, o.reserved_buf)
        && equals(req_type, o.req_type);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = reserved_buf != null ? reserved_buf.hashCode() : 0;
      result = result * 37 + (req_type != null ? req_type.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<GetUserTaskListReq> {

    public ByteString reserved_buf;
    public Integer req_type;

    public Builder() {
    }

    public Builder(GetUserTaskListReq message) {
      super(message);
      if (message == null) return;
      this.reserved_buf = message.reserved_buf;
      this.req_type = message.req_type;
    }

    public Builder reserved_buf(ByteString reserved_buf) {
      this.reserved_buf = reserved_buf;
      return this;
    }

    /**
     * 服务端使用，客户端忽略
     */
    public Builder req_type(Integer req_type) {
      this.req_type = req_type;
      return this;
    }

    @Override
    public GetUserTaskListReq build() {
      return new GetUserTaskListReq(this);
    }
  }
}
