// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\profile.proto
package com.wesocial.apollo.protocol.protobuf.profile;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;
import okio.ByteString;

import static com.squareup.wire.Message.Datatype.BYTES;
import static com.squareup.wire.Message.Datatype.UINT32;

public final class GetUserTaskNewRsp extends Message {
  private static final long serialVersionUID = 0L;

  public static final ByteString DEFAULT_RESERVED_BUF = ByteString.EMPTY;
  public static final Integer DEFAULT_NEW_NUM = 0;

  @ProtoField(tag = 1, type = BYTES)
  public final ByteString reserved_buf;

  /**
   * 服务端使用，客户端忽略
   */
  @ProtoField(tag = 2, type = UINT32)
  public final Integer new_num;

  public GetUserTaskNewRsp(ByteString reserved_buf, Integer new_num) {
    this.reserved_buf = reserved_buf;
    this.new_num = new_num;
  }

  private GetUserTaskNewRsp(Builder builder) {
    this(builder.reserved_buf, builder.new_num);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof GetUserTaskNewRsp)) return false;
    GetUserTaskNewRsp o = (GetUserTaskNewRsp) other;
    return equals(reserved_buf, o.reserved_buf)
        && equals(new_num, o.new_num);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = reserved_buf != null ? reserved_buf.hashCode() : 0;
      result = result * 37 + (new_num != null ? new_num.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<GetUserTaskNewRsp> {

    public ByteString reserved_buf;
    public Integer new_num;

    public Builder() {
    }

    public Builder(GetUserTaskNewRsp message) {
      super(message);
      if (message == null) return;
      this.reserved_buf = message.reserved_buf;
      this.new_num = message.new_num;
    }

    public Builder reserved_buf(ByteString reserved_buf) {
      this.reserved_buf = reserved_buf;
      return this;
    }

    /**
     * 服务端使用，客户端忽略
     */
    public Builder new_num(Integer new_num) {
      this.new_num = new_num;
      return this;
    }

    @Override
    public GetUserTaskNewRsp build() {
      return new GetUserTaskNewRsp(this);
    }
  }
}
