// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\profile.proto
package com.wesocial.apollo.protocol.protobuf.profile;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.STRING;

/**
 * 礼包详情
 */
public final class GiftContent extends Message {
  private static final long serialVersionUID = 0L;

  public static final String DEFAULT_TEXT = "";
  public static final String DEFAULT_IMAGE = "";
  public static final String DEFAULT_NUM = "";

  @ProtoField(tag = 1, type = STRING)
  public final String text;

  /**
   * 物品名称
   */
  @ProtoField(tag = 2, type = STRING)
  public final String image;

  /**
   * 物品图片
   */
  @ProtoField(tag = 3, type = STRING)
  public final String num;

  public GiftContent(String text, String image, String num) {
    this.text = text;
    this.image = image;
    this.num = num;
  }

  private GiftContent(Builder builder) {
    this(builder.text, builder.image, builder.num);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof GiftContent)) return false;
    GiftContent o = (GiftContent) other;
    return equals(text, o.text)
        && equals(image, o.image)
        && equals(num, o.num);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = text != null ? text.hashCode() : 0;
      result = result * 37 + (image != null ? image.hashCode() : 0);
      result = result * 37 + (num != null ? num.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<GiftContent> {

    public String text;
    public String image;
    public String num;

    public Builder() {
    }

    public Builder(GiftContent message) {
      super(message);
      if (message == null) return;
      this.text = message.text;
      this.image = message.image;
      this.num = message.num;
    }

    public Builder text(String text) {
      this.text = text;
      return this;
    }

    /**
     * 物品名称
     */
    public Builder image(String image) {
      this.image = image;
      return this;
    }

    /**
     * 物品图片
     */
    public Builder num(String num) {
      this.num = num;
      return this;
    }

    @Override
    public GiftContent build() {
      return new GiftContent(this);
    }
  }
}
