// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\profile.proto
package com.wesocial.apollo.protocol.protobuf.profile;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;
import java.util.Collections;
import java.util.List;

import static com.squareup.wire.Message.Datatype.STRING;
import static com.squareup.wire.Message.Label.REPEATED;

/**
 * 礼包活动列表
 */
public final class GiftActivityList extends Message {
  private static final long serialVersionUID = 0L;

  public static final List<GiftActivity> DEFAULT_GIFT_ACTIVITY_LIST = Collections.emptyList();
  public static final String DEFAULT_MESSAGE_TITLE = "";
  public static final String DEFAULT_MESSAGE_TEXT = "";
  public static final String DEFAULT_REGISTER_MESSAGE = "";

  @ProtoField(tag = 1, label = REPEATED, messageType = GiftActivity.class)
  public final List<GiftActivity> gift_activity_list;

  @ProtoField(tag = 2, type = STRING)
  public final String message_title;

  @ProtoField(tag = 3, type = STRING)
  public final String message_text;

  @ProtoField(tag = 4, type = STRING)
  public final String register_message;

  public GiftActivityList(List<GiftActivity> gift_activity_list, String message_title, String message_text, String register_message) {
    this.gift_activity_list = immutableCopyOf(gift_activity_list);
    this.message_title = message_title;
    this.message_text = message_text;
    this.register_message = register_message;
  }

  private GiftActivityList(Builder builder) {
    this(builder.gift_activity_list, builder.message_title, builder.message_text, builder.register_message);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof GiftActivityList)) return false;
    GiftActivityList o = (GiftActivityList) other;
    return equals(gift_activity_list, o.gift_activity_list)
        && equals(message_title, o.message_title)
        && equals(message_text, o.message_text)
        && equals(register_message, o.register_message);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = gift_activity_list != null ? gift_activity_list.hashCode() : 1;
      result = result * 37 + (message_title != null ? message_title.hashCode() : 0);
      result = result * 37 + (message_text != null ? message_text.hashCode() : 0);
      result = result * 37 + (register_message != null ? register_message.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<GiftActivityList> {

    public List<GiftActivity> gift_activity_list;
    public String message_title;
    public String message_text;
    public String register_message;

    public Builder() {
    }

    public Builder(GiftActivityList message) {
      super(message);
      if (message == null) return;
      this.gift_activity_list = copyOf(message.gift_activity_list);
      this.message_title = message.message_title;
      this.message_text = message.message_text;
      this.register_message = message.register_message;
    }

    public Builder gift_activity_list(List<GiftActivity> gift_activity_list) {
      this.gift_activity_list = checkForNulls(gift_activity_list);
      return this;
    }

    public Builder message_title(String message_title) {
      this.message_title = message_title;
      return this;
    }

    public Builder message_text(String message_text) {
      this.message_text = message_text;
      return this;
    }

    public Builder register_message(String register_message) {
      this.register_message = register_message;
      return this;
    }

    @Override
    public GiftActivityList build() {
      return new GiftActivityList(this);
    }
  }
}
