// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\profile.proto
package com.wesocial.apollo.protocol.protobuf.profile;

import com.squareup.wire.ProtoEnum;

public enum HeadOpType
    implements ProtoEnum {
  kHeadAdd(1),
  kHeadModify(2),
  kHeadDel(3);

  private final int value;

  private HeadOpType(int value) {
    this.value = value;
  }

  @Override
  public int getValue() {
    return value;
  }
}
