// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\profile.proto
package com.wesocial.apollo.protocol.protobuf.profile;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.INT32;
import static com.squareup.wire.Message.Datatype.STRING;

/**
 * 头像信息,头像发生变化时，只上传有变化的Url和位置
 */
public final class HeadUrlInfo extends Message {
  private static final long serialVersionUID = 0L;

  public static final String DEFAULT_URL = "";
  public static final Integer DEFAULT_INDEX = 0;
  public static final Integer DEFAULT_OPTYPE = 0;

  @ProtoField(tag = 1, type = STRING)
  public final String url;

  /**
   * 头像URL
   */
  @ProtoField(tag = 2, type = INT32)
  public final Integer index;

  /**
   * 头像位置，从1开始
   */
  @ProtoField(tag = 3, type = INT32)
  public final Integer optype;

  public HeadUrlInfo(String url, Integer index, Integer optype) {
    this.url = url;
    this.index = index;
    this.optype = optype;
  }

  private HeadUrlInfo(Builder builder) {
    this(builder.url, builder.index, builder.optype);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof HeadUrlInfo)) return false;
    HeadUrlInfo o = (HeadUrlInfo) other;
    return equals(url, o.url)
        && equals(index, o.index)
        && equals(optype, o.optype);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = url != null ? url.hashCode() : 0;
      result = result * 37 + (index != null ? index.hashCode() : 0);
      result = result * 37 + (optype != null ? optype.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<HeadUrlInfo> {

    public String url;
    public Integer index;
    public Integer optype;

    public Builder() {
    }

    public Builder(HeadUrlInfo message) {
      super(message);
      if (message == null) return;
      this.url = message.url;
      this.index = message.index;
      this.optype = message.optype;
    }

    public Builder url(String url) {
      this.url = url;
      return this;
    }

    /**
     * 头像URL
     */
    public Builder index(Integer index) {
      this.index = index;
      return this;
    }

    /**
     * 头像位置，从1开始
     */
    public Builder optype(Integer optype) {
      this.optype = optype;
      return this;
    }

    @Override
    public HeadUrlInfo build() {
      return new HeadUrlInfo(this);
    }
  }
}
