// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\profile.proto
package com.wesocial.apollo.protocol.protobuf.profile;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;
import java.util.Collections;
import java.util.List;

import static com.squareup.wire.Message.Datatype.UINT32;
import static com.squareup.wire.Message.Label.REPEATED;

/**
 * rank user list
 */
public final class RankUserList extends Message {
  private static final long serialVersionUID = 0L;

  public static final List<AllUserInfo> DEFAULT_USER_LIST = Collections.emptyList();
  public static final Integer DEFAULT_VERSION = 0;
  public static final Integer DEFAULT_TOTAL_NUM = 0;

  @ProtoField(tag = 1, label = REPEATED, messageType = AllUserInfo.class)
  public final List<AllUserInfo> user_list;

  @ProtoField(tag = 2, type = UINT32)
  public final Integer version;

  /**
   * 版本号
   */
  @ProtoField(tag = 3, type = UINT32)
  public final Integer total_num;

  public RankUserList(List<AllUserInfo> user_list, Integer version, Integer total_num) {
    this.user_list = immutableCopyOf(user_list);
    this.version = version;
    this.total_num = total_num;
  }

  private RankUserList(Builder builder) {
    this(builder.user_list, builder.version, builder.total_num);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof RankUserList)) return false;
    RankUserList o = (RankUserList) other;
    return equals(user_list, o.user_list)
        && equals(version, o.version)
        && equals(total_num, o.total_num);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = user_list != null ? user_list.hashCode() : 1;
      result = result * 37 + (version != null ? version.hashCode() : 0);
      result = result * 37 + (total_num != null ? total_num.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<RankUserList> {

    public List<AllUserInfo> user_list;
    public Integer version;
    public Integer total_num;

    public Builder() {
    }

    public Builder(RankUserList message) {
      super(message);
      if (message == null) return;
      this.user_list = copyOf(message.user_list);
      this.version = message.version;
      this.total_num = message.total_num;
    }

    public Builder user_list(List<AllUserInfo> user_list) {
      this.user_list = checkForNulls(user_list);
      return this;
    }

    public Builder version(Integer version) {
      this.version = version;
      return this;
    }

    /**
     * 版本号
     */
    public Builder total_num(Integer total_num) {
      this.total_num = total_num;
      return this;
    }

    @Override
    public RankUserList build() {
      return new RankUserList(this);
    }
  }
}
