// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\profile.proto
package com.wesocial.apollo.protocol.protobuf.profile;

import com.squareup.wire.ProtoEnum;

public enum RegisterType
    implements ProtoEnum {
  kRegisterNo(0),
  /**
   * 未注册
   */
  kRegisterPart(1),
  /**
   * 部分注册
   */
  kRegisterAll(2),
  /**
   * 全注册
   */
  kForbidden(3);

  private final int value;

  private RegisterType(int value) {
    this.value = value;
  }

  @Override
  public int getValue() {
    return value;
  }
}
