// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\profile.proto
package com.wesocial.apollo.protocol.protobuf.profile;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;
import okio.ByteString;

import static com.squareup.wire.Message.Datatype.BYTES;
import static com.squareup.wire.Message.Datatype.INT32;
import static com.squareup.wire.Message.Datatype.UINT64;

/**
 * XVI. 举报用户
 * CMD为REPORT_USER （109）
 */
public final class ReportUserReq extends Message {
  private static final long serialVersionUID = 0L;

  public static final ByteString DEFAULT_RESERVED_BUF = ByteString.EMPTY;
  public static final Long DEFAULT_INNER_ID = 0L;
  public static final Integer DEFAULT_REASON = 0;

  @ProtoField(tag = 1, type = BYTES)
  public final ByteString reserved_buf;

  /**
   * 服务端使用，客户端忽略
   */
  @ProtoField(tag = 2, type = UINT64)
  public final Long inner_id;

  /**
   * 举报对象的inner id
   */
  @ProtoField(tag = 3, type = INT32)
  public final Integer reason;

  public ReportUserReq(ByteString reserved_buf, Long inner_id, Integer reason) {
    this.reserved_buf = reserved_buf;
    this.inner_id = inner_id;
    this.reason = reason;
  }

  private ReportUserReq(Builder builder) {
    this(builder.reserved_buf, builder.inner_id, builder.reason);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof ReportUserReq)) return false;
    ReportUserReq o = (ReportUserReq) other;
    return equals(reserved_buf, o.reserved_buf)
        && equals(inner_id, o.inner_id)
        && equals(reason, o.reason);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = reserved_buf != null ? reserved_buf.hashCode() : 0;
      result = result * 37 + (inner_id != null ? inner_id.hashCode() : 0);
      result = result * 37 + (reason != null ? reason.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<ReportUserReq> {

    public ByteString reserved_buf;
    public Long inner_id;
    public Integer reason;

    public Builder() {
    }

    public Builder(ReportUserReq message) {
      super(message);
      if (message == null) return;
      this.reserved_buf = message.reserved_buf;
      this.inner_id = message.inner_id;
      this.reason = message.reason;
    }

    public Builder reserved_buf(ByteString reserved_buf) {
      this.reserved_buf = reserved_buf;
      return this;
    }

    /**
     * 服务端使用，客户端忽略
     */
    public Builder inner_id(Long inner_id) {
      this.inner_id = inner_id;
      return this;
    }

    /**
     * 举报对象的inner id
     */
    public Builder reason(Integer reason) {
      this.reason = reason;
      return this;
    }

    @Override
    public ReportUserReq build() {
      return new ReportUserReq(this);
    }
  }
}
