// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\profile.proto
package com.wesocial.apollo.protocol.protobuf.profile;

import com.squareup.wire.ProtoEnum;

public enum SendFlowerType
    implements ProtoEnum {
  kSendFlowerSendQq(1),
  /**
   * 分享QQ
   */
  kSendFLowerSendWeixin(2),
  /**
   * 分享微信
   */
  kSendFlowerShareFriend(3),
  /**
   * 分享朋友圈
   */
  kSendFlowerReview(4),
  /**
   * appstore评价
   */
  kSendFlowerContinueLogin(5);

  private final int value;

  private SendFlowerType(int value) {
    this.value = value;
  }

  @Override
  public int getValue() {
    return value;
  }
}
