// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\profile.proto
package com.wesocial.apollo.protocol.protobuf.profile;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;
import okio.ByteString;

import static com.squareup.wire.Message.Datatype.BYTES;
import static com.squareup.wire.Message.Datatype.UINT32;

/**
 * TAKE_TASK_GOLD 209
 * 领取任务奖励
 */
public final class TakeTaskGoldReq extends Message {
  private static final long serialVersionUID = 0L;

  public static final ByteString DEFAULT_RESERVED_BUF = ByteString.EMPTY;
  public static final Integer DEFAULT_TASK_ID = 0;

  @ProtoField(tag = 1, type = BYTES)
  public final ByteString reserved_buf;

  /**
   * 服务端使用，客户端忽略
   */
  @ProtoField(tag = 2, type = UINT32)
  public final Integer task_id;

  public TakeTaskGoldReq(ByteString reserved_buf, Integer task_id) {
    this.reserved_buf = reserved_buf;
    this.task_id = task_id;
  }

  private TakeTaskGoldReq(Builder builder) {
    this(builder.reserved_buf, builder.task_id);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof TakeTaskGoldReq)) return false;
    TakeTaskGoldReq o = (TakeTaskGoldReq) other;
    return equals(reserved_buf, o.reserved_buf)
        && equals(task_id, o.task_id);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = reserved_buf != null ? reserved_buf.hashCode() : 0;
      result = result * 37 + (task_id != null ? task_id.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<TakeTaskGoldReq> {

    public ByteString reserved_buf;
    public Integer task_id;

    public Builder() {
    }

    public Builder(TakeTaskGoldReq message) {
      super(message);
      if (message == null) return;
      this.reserved_buf = message.reserved_buf;
      this.task_id = message.task_id;
    }

    public Builder reserved_buf(ByteString reserved_buf) {
      this.reserved_buf = reserved_buf;
      return this;
    }

    /**
     * 服务端使用，客户端忽略
     */
    public Builder task_id(Integer task_id) {
      this.task_id = task_id;
      return this;
    }

    @Override
    public TakeTaskGoldReq build() {
      return new TakeTaskGoldReq(this);
    }
  }
}
