// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\profile.proto
package com.wesocial.apollo.protocol.protobuf.profile;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.STRING;
import static com.squareup.wire.Message.Datatype.UINT32;

public final class UserTask extends Message {
  private static final long serialVersionUID = 0L;

  public static final Integer DEFAULT_ID = 0;
  public static final Integer DEFAULT_TYPE = 0;
  public static final String DEFAULT_NAME = "";
  public static final String DEFAULT_DESC = "";
  public static final Integer DEFAULT_STATUS = 0;
  public static final Integer DEFAULT_PROGRESS = 0;
  public static final Integer DEFAULT_TOTAL = 0;
  public static final Integer DEFAULT_GOLD_NUM = 0;
  public static final String DEFAULT_GO_URL = "";

  @ProtoField(tag = 1, type = UINT32)
  public final Integer id;

  /**
   * 任务ID
   */
  @ProtoField(tag = 2, type = UINT32)
  public final Integer type;

  /**
   * 任务类型 1 新手， 2 日常
   */
  @ProtoField(tag = 3, type = STRING)
  public final String name;

  /**
   * 任务名
   */
  @ProtoField(tag = 4, type = STRING)
  public final String desc;

  /**
   * 任务描述
   */
  @ProtoField(tag = 5, type = UINT32)
  public final Integer status;

  /**
   * 任务状态, 1 进行中， 2 任务完成， 等待用户领取奖励， 3 用户已经领取了奖励
   */
  @ProtoField(tag = 6, type = UINT32)
  public final Integer progress;

  /**
   * 任务进度
   */
  @ProtoField(tag = 7, type = UINT32)
  public final Integer total;

  /**
   * 任务需要完成的步骤数
   */
  @ProtoField(tag = 8, type = UINT32)
  public final Integer gold_num;

  /**
   * 任务奖励的金币数
   */
  @ProtoField(tag = 9, type = STRING)
  public final String go_url;

  public UserTask(Integer id, Integer type, String name, String desc, Integer status, Integer progress, Integer total, Integer gold_num, String go_url) {
    this.id = id;
    this.type = type;
    this.name = name;
    this.desc = desc;
    this.status = status;
    this.progress = progress;
    this.total = total;
    this.gold_num = gold_num;
    this.go_url = go_url;
  }

  private UserTask(Builder builder) {
    this(builder.id, builder.type, builder.name, builder.desc, builder.status, builder.progress, builder.total, builder.gold_num, builder.go_url);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof UserTask)) return false;
    UserTask o = (UserTask) other;
    return equals(id, o.id)
        && equals(type, o.type)
        && equals(name, o.name)
        && equals(desc, o.desc)
        && equals(status, o.status)
        && equals(progress, o.progress)
        && equals(total, o.total)
        && equals(gold_num, o.gold_num)
        && equals(go_url, o.go_url);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = id != null ? id.hashCode() : 0;
      result = result * 37 + (type != null ? type.hashCode() : 0);
      result = result * 37 + (name != null ? name.hashCode() : 0);
      result = result * 37 + (desc != null ? desc.hashCode() : 0);
      result = result * 37 + (status != null ? status.hashCode() : 0);
      result = result * 37 + (progress != null ? progress.hashCode() : 0);
      result = result * 37 + (total != null ? total.hashCode() : 0);
      result = result * 37 + (gold_num != null ? gold_num.hashCode() : 0);
      result = result * 37 + (go_url != null ? go_url.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<UserTask> {

    public Integer id;
    public Integer type;
    public String name;
    public String desc;
    public Integer status;
    public Integer progress;
    public Integer total;
    public Integer gold_num;
    public String go_url;

    public Builder() {
    }

    public Builder(UserTask message) {
      super(message);
      if (message == null) return;
      this.id = message.id;
      this.type = message.type;
      this.name = message.name;
      this.desc = message.desc;
      this.status = message.status;
      this.progress = message.progress;
      this.total = message.total;
      this.gold_num = message.gold_num;
      this.go_url = message.go_url;
    }

    public Builder id(Integer id) {
      this.id = id;
      return this;
    }

    /**
     * 任务ID
     */
    public Builder type(Integer type) {
      this.type = type;
      return this;
    }

    /**
     * 任务类型 1 新手， 2 日常
     */
    public Builder name(String name) {
      this.name = name;
      return this;
    }

    /**
     * 任务名
     */
    public Builder desc(String desc) {
      this.desc = desc;
      return this;
    }

    /**
     * 任务描述
     */
    public Builder status(Integer status) {
      this.status = status;
      return this;
    }

    /**
     * 任务状态, 1 进行中， 2 任务完成， 等待用户领取奖励， 3 用户已经领取了奖励
     */
    public Builder progress(Integer progress) {
      this.progress = progress;
      return this;
    }

    /**
     * 任务进度
     */
    public Builder total(Integer total) {
      this.total = total;
      return this;
    }

    /**
     * 任务需要完成的步骤数
     */
    public Builder gold_num(Integer gold_num) {
      this.gold_num = gold_num;
      return this;
    }

    /**
     * 任务奖励的金币数
     */
    public Builder go_url(String go_url) {
      this.go_url = go_url;
      return this;
    }

    @Override
    public UserTask build() {
      return new UserTask(this);
    }
  }
}
