// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\profile.proto
package com.wesocial.apollo.protocol.protobuf.profile;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.UINT32;

/**
 * base_version为基础信息加上第一张头像所对应的版本号
 * extra_version为扩展信息对应的版本号
 * pic_version为除第一张头像外对应的版本号
 */
public final class UserVersion extends Message {
  private static final long serialVersionUID = 0L;

  public static final Integer DEFAULT_BASE_VERSION = 0;
  public static final Integer DEFAULT_EXTRA_VERSION = 0;
  public static final Integer DEFAULT_PIC_VERSION = 0;

  @ProtoField(tag = 1, type = UINT32)
  public final Integer base_version;

  @ProtoField(tag = 2, type = UINT32)
  public final Integer extra_version;

  @ProtoField(tag = 3, type = UINT32)
  public final Integer pic_version;

  public UserVersion(Integer base_version, Integer extra_version, Integer pic_version) {
    this.base_version = base_version;
    this.extra_version = extra_version;
    this.pic_version = pic_version;
  }

  private UserVersion(Builder builder) {
    this(builder.base_version, builder.extra_version, builder.pic_version);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof UserVersion)) return false;
    UserVersion o = (UserVersion) other;
    return equals(base_version, o.base_version)
        && equals(extra_version, o.extra_version)
        && equals(pic_version, o.pic_version);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = base_version != null ? base_version.hashCode() : 0;
      result = result * 37 + (extra_version != null ? extra_version.hashCode() : 0);
      result = result * 37 + (pic_version != null ? pic_version.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<UserVersion> {

    public Integer base_version;
    public Integer extra_version;
    public Integer pic_version;

    public Builder() {
    }

    public Builder(UserVersion message) {
      super(message);
      if (message == null) return;
      this.base_version = message.base_version;
      this.extra_version = message.extra_version;
      this.pic_version = message.pic_version;
    }

    public Builder base_version(Integer base_version) {
      this.base_version = base_version;
      return this;
    }

    public Builder extra_version(Integer extra_version) {
      this.extra_version = extra_version;
      return this;
    }

    public Builder pic_version(Integer pic_version) {
      this.pic_version = pic_version;
      return this;
    }

    @Override
    public UserVersion build() {
      return new UserVersion(this);
    }
  }
}
