// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\misc.proto
package com.wesocial.apollo.protocol.protobuf.misc;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;
import java.util.Collections;
import java.util.List;
import okio.ByteString;

import static com.squareup.wire.Message.Datatype.BYTES;
import static com.squareup.wire.Message.Label.REPEATED;

public final class BatchGetConfigsRsp extends Message {
  private static final long serialVersionUID = 0L;

  public static final ByteString DEFAULT_RESERVED_BUF = ByteString.EMPTY;
  public static final List<ConfigInfo> DEFAULT_CONFIG_INFOS = Collections.emptyList();

  @ProtoField(tag = 1, type = BYTES)
  public final ByteString reserved_buf;

  /**
   * 服务端使用，客户端忽略
   */
  @ProtoField(tag = 2, label = REPEATED, messageType = ConfigInfo.class)
  public final List<ConfigInfo> config_infos;

  public BatchGetConfigsRsp(ByteString reserved_buf, List<ConfigInfo> config_infos) {
    this.reserved_buf = reserved_buf;
    this.config_infos = immutableCopyOf(config_infos);
  }

  private BatchGetConfigsRsp(Builder builder) {
    this(builder.reserved_buf, builder.config_infos);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof BatchGetConfigsRsp)) return false;
    BatchGetConfigsRsp o = (BatchGetConfigsRsp) other;
    return equals(reserved_buf, o.reserved_buf)
        && equals(config_infos, o.config_infos);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = reserved_buf != null ? reserved_buf.hashCode() : 0;
      result = result * 37 + (config_infos != null ? config_infos.hashCode() : 1);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<BatchGetConfigsRsp> {

    public ByteString reserved_buf;
    public List<ConfigInfo> config_infos;

    public Builder() {
    }

    public Builder(BatchGetConfigsRsp message) {
      super(message);
      if (message == null) return;
      this.reserved_buf = message.reserved_buf;
      this.config_infos = copyOf(message.config_infos);
    }

    public Builder reserved_buf(ByteString reserved_buf) {
      this.reserved_buf = reserved_buf;
      return this;
    }

    /**
     * 服务端使用，客户端忽略
     */
    public Builder config_infos(List<ConfigInfo> config_infos) {
      this.config_infos = checkForNulls(config_infos);
      return this;
    }

    @Override
    public BatchGetConfigsRsp build() {
      return new BatchGetConfigsRsp(this);
    }
  }
}
