// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\misc.proto
package com.wesocial.apollo.protocol.protobuf.misc;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;
import okio.ByteString;

import static com.squareup.wire.Message.Datatype.BYTES;
import static com.squareup.wire.Message.Datatype.INT32;
import static com.squareup.wire.Message.Datatype.UINT64;

/**
 * 举报文章
 */
public final class ReportArticleReq extends Message {
  private static final long serialVersionUID = 0L;

  public static final ByteString DEFAULT_RESERVED_BUF = ByteString.EMPTY;
  public static final Long DEFAULT_AUTHOR_INNER_ID = 0L;
  public static final Long DEFAULT_ARTICLE_ID = 0L;
  public static final Integer DEFAULT_REASON = 0;

  @ProtoField(tag = 1, type = BYTES)
  public final ByteString reserved_buf;

  /**
   * 服务端使用，客户端忽略
   */
  @ProtoField(tag = 2, type = UINT64)
  public final Long author_inner_id;

  /**
   * 文章作者inner id
   */
  @ProtoField(tag = 3, type = UINT64)
  public final Long article_id;

  /**
   * 文章id
   */
  @ProtoField(tag = 4, type = INT32)
  public final Integer reason;

  public ReportArticleReq(ByteString reserved_buf, Long author_inner_id, Long article_id, Integer reason) {
    this.reserved_buf = reserved_buf;
    this.author_inner_id = author_inner_id;
    this.article_id = article_id;
    this.reason = reason;
  }

  private ReportArticleReq(Builder builder) {
    this(builder.reserved_buf, builder.author_inner_id, builder.article_id, builder.reason);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof ReportArticleReq)) return false;
    ReportArticleReq o = (ReportArticleReq) other;
    return equals(reserved_buf, o.reserved_buf)
        && equals(author_inner_id, o.author_inner_id)
        && equals(article_id, o.article_id)
        && equals(reason, o.reason);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = reserved_buf != null ? reserved_buf.hashCode() : 0;
      result = result * 37 + (author_inner_id != null ? author_inner_id.hashCode() : 0);
      result = result * 37 + (article_id != null ? article_id.hashCode() : 0);
      result = result * 37 + (reason != null ? reason.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<ReportArticleReq> {

    public ByteString reserved_buf;
    public Long author_inner_id;
    public Long article_id;
    public Integer reason;

    public Builder() {
    }

    public Builder(ReportArticleReq message) {
      super(message);
      if (message == null) return;
      this.reserved_buf = message.reserved_buf;
      this.author_inner_id = message.author_inner_id;
      this.article_id = message.article_id;
      this.reason = message.reason;
    }

    public Builder reserved_buf(ByteString reserved_buf) {
      this.reserved_buf = reserved_buf;
      return this;
    }

    /**
     * 服务端使用，客户端忽略
     */
    public Builder author_inner_id(Long author_inner_id) {
      this.author_inner_id = author_inner_id;
      return this;
    }

    /**
     * 文章作者inner id
     */
    public Builder article_id(Long article_id) {
      this.article_id = article_id;
      return this;
    }

    /**
     * 文章id
     */
    public Builder reason(Integer reason) {
      this.reason = reason;
      return this;
    }

    @Override
    public ReportArticleReq build() {
      return new ReportArticleReq(this);
    }
  }
}
