// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\login.proto
package com.wesocial.apollo.protocol.protobuf.login;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;
import okio.ByteString;

import static com.squareup.wire.Message.Datatype.BYTES;
import static com.squareup.wire.Message.Datatype.INT32;
import static com.squareup.wire.Message.Datatype.UINT64;

public final class CommonLoginRsp extends Message {
  private static final long serialVersionUID = 0L;

  public static final ByteString DEFAULT_RESERVED_BUF = ByteString.EMPTY;
  public static final ByteString DEFAULT_TICK_INFO = ByteString.EMPTY;
  public static final Long DEFAULT_INNER_ID = 0L;
  public static final Integer DEFAULT_USER_STATUS = 0;

  @ProtoField(tag = 1, type = BYTES)
  public final ByteString reserved_buf;

  /**
   * 服务端使用，客户端忽略
   */
  @ProtoField(tag = 2, type = BYTES)
  public final ByteString tick_info;

  /**
   * 票据相关信息(用AES密钥加密TicketMsg生成)
   */
  @ProtoField(tag = 3, type = UINT64)
  public final Long inner_id;

  /**
   * 用户内部id
   */
  @ProtoField(tag = 4, type = INT32)
  public final Integer user_status;

  public CommonLoginRsp(ByteString reserved_buf, ByteString tick_info, Long inner_id, Integer user_status) {
    this.reserved_buf = reserved_buf;
    this.tick_info = tick_info;
    this.inner_id = inner_id;
    this.user_status = user_status;
  }

  private CommonLoginRsp(Builder builder) {
    this(builder.reserved_buf, builder.tick_info, builder.inner_id, builder.user_status);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof CommonLoginRsp)) return false;
    CommonLoginRsp o = (CommonLoginRsp) other;
    return equals(reserved_buf, o.reserved_buf)
        && equals(tick_info, o.tick_info)
        && equals(inner_id, o.inner_id)
        && equals(user_status, o.user_status);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = reserved_buf != null ? reserved_buf.hashCode() : 0;
      result = result * 37 + (tick_info != null ? tick_info.hashCode() : 0);
      result = result * 37 + (inner_id != null ? inner_id.hashCode() : 0);
      result = result * 37 + (user_status != null ? user_status.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<CommonLoginRsp> {

    public ByteString reserved_buf;
    public ByteString tick_info;
    public Long inner_id;
    public Integer user_status;

    public Builder() {
    }

    public Builder(CommonLoginRsp message) {
      super(message);
      if (message == null) return;
      this.reserved_buf = message.reserved_buf;
      this.tick_info = message.tick_info;
      this.inner_id = message.inner_id;
      this.user_status = message.user_status;
    }

    public Builder reserved_buf(ByteString reserved_buf) {
      this.reserved_buf = reserved_buf;
      return this;
    }

    /**
     * 服务端使用，客户端忽略
     */
    public Builder tick_info(ByteString tick_info) {
      this.tick_info = tick_info;
      return this;
    }

    /**
     * 票据相关信息(用AES密钥加密TicketMsg生成)
     */
    public Builder inner_id(Long inner_id) {
      this.inner_id = inner_id;
      return this;
    }

    /**
     * 用户内部id
     */
    public Builder user_status(Integer user_status) {
      this.user_status = user_status;
      return this;
    }

    @Override
    public CommonLoginRsp build() {
      return new CommonLoginRsp(this);
    }
  }
}
