// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\login.proto
package com.wesocial.apollo.protocol.protobuf.login;

import com.squareup.wire.ProtoEnum;

public enum EncryptType
    implements ProtoEnum {
  kEncryptByNone(1),
  /**
   * 不加密
   */
  kEncryptByAES(2);

  private final int value;

  private EncryptType(int value) {
    this.value = value;
  }

  @Override
  public int getValue() {
    return value;
  }
}
