// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\login.proto
package com.wesocial.apollo.protocol.protobuf.login;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;
import okio.ByteString;

import static com.squareup.wire.Message.Datatype.BYTES;

public final class ExchangeTicketRsp extends Message {
  private static final long serialVersionUID = 0L;

  public static final ByteString DEFAULT_RESERVED_BUF = ByteString.EMPTY;
  public static final ByteString DEFAULT_TICK_INFO = ByteString.EMPTY;

  @ProtoField(tag = 1, type = BYTES)
  public final ByteString reserved_buf;

  /**
   * 服务端使用，客户端忽略
   */
  @ProtoField(tag = 2, type = BYTES)
  public final ByteString tick_info;

  public ExchangeTicketRsp(ByteString reserved_buf, ByteString tick_info) {
    this.reserved_buf = reserved_buf;
    this.tick_info = tick_info;
  }

  private ExchangeTicketRsp(Builder builder) {
    this(builder.reserved_buf, builder.tick_info);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof ExchangeTicketRsp)) return false;
    ExchangeTicketRsp o = (ExchangeTicketRsp) other;
    return equals(reserved_buf, o.reserved_buf)
        && equals(tick_info, o.tick_info);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = reserved_buf != null ? reserved_buf.hashCode() : 0;
      result = result * 37 + (tick_info != null ? tick_info.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<ExchangeTicketRsp> {

    public ByteString reserved_buf;
    public ByteString tick_info;

    public Builder() {
    }

    public Builder(ExchangeTicketRsp message) {
      super(message);
      if (message == null) return;
      this.reserved_buf = message.reserved_buf;
      this.tick_info = message.tick_info;
    }

    public Builder reserved_buf(ByteString reserved_buf) {
      this.reserved_buf = reserved_buf;
      return this;
    }

    /**
     * 服务端使用，客户端忽略
     */
    public Builder tick_info(ByteString tick_info) {
      this.tick_info = tick_info;
      return this;
    }

    @Override
    public ExchangeTicketRsp build() {
      return new ExchangeTicketRsp(this);
    }
  }
}
