// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\login.proto
package com.wesocial.apollo.protocol.protobuf.login;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.STRING;

public final class LoginId extends Message {
  private static final long serialVersionUID = 0L;

  public static final String DEFAULT_OPENID = "";

  @ProtoField(tag = 1)
  public final Mobile mobile_info;

  /**
   * 手机信息
   */
  @ProtoField(tag = 2, type = STRING)
  public final String openid;

  public LoginId(Mobile mobile_info, String openid) {
    this.mobile_info = mobile_info;
    this.openid = openid;
  }

  private LoginId(Builder builder) {
    this(builder.mobile_info, builder.openid);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof LoginId)) return false;
    LoginId o = (LoginId) other;
    return equals(mobile_info, o.mobile_info)
        && equals(openid, o.openid);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = mobile_info != null ? mobile_info.hashCode() : 0;
      result = result * 37 + (openid != null ? openid.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<LoginId> {

    public Mobile mobile_info;
    public String openid;

    public Builder() {
    }

    public Builder(LoginId message) {
      super(message);
      if (message == null) return;
      this.mobile_info = message.mobile_info;
      this.openid = message.openid;
    }

    public Builder mobile_info(Mobile mobile_info) {
      this.mobile_info = mobile_info;
      return this;
    }

    /**
     * 手机信息
     */
    public Builder openid(String openid) {
      this.openid = openid;
      return this;
    }

    @Override
    public LoginId build() {
      return new LoginId(this);
    }
  }
}
