// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\login.proto
package com.wesocial.apollo.protocol.protobuf.login;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.STRING;

public final class Mobile extends Message {
  private static final long serialVersionUID = 0L;

  public static final String DEFAULT_COUNTRY_CODE = "";
  public static final String DEFAULT_MOBILE_NUM = "";

  @ProtoField(tag = 1, type = STRING)
  public final String country_code;

  /**
   * 国家代码
   */
  @ProtoField(tag = 2, type = STRING)
  public final String mobile_num;

  public Mobile(String country_code, String mobile_num) {
    this.country_code = country_code;
    this.mobile_num = mobile_num;
  }

  private Mobile(Builder builder) {
    this(builder.country_code, builder.mobile_num);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof Mobile)) return false;
    Mobile o = (Mobile) other;
    return equals(country_code, o.country_code)
        && equals(mobile_num, o.mobile_num);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = country_code != null ? country_code.hashCode() : 0;
      result = result * 37 + (mobile_num != null ? mobile_num.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<Mobile> {

    public String country_code;
    public String mobile_num;

    public Builder() {
    }

    public Builder(Mobile message) {
      super(message);
      if (message == null) return;
      this.country_code = message.country_code;
      this.mobile_num = message.mobile_num;
    }

    public Builder country_code(String country_code) {
      this.country_code = country_code;
      return this;
    }

    /**
     * 国家代码
     */
    public Builder mobile_num(String mobile_num) {
      this.mobile_num = mobile_num;
      return this;
    }

    @Override
    public Mobile build() {
      return new Mobile(this);
    }
  }
}
