// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\friend.proto
package com.wesocial.apollo.protocol.protobuf.friend;

import com.squareup.wire.ProtoEnum;

public enum FriendType
    implements ProtoEnum {
  kTypeFollowed(1),
  /**
   * 已关注
   */
  kTypeFans(2),
  /**
   * 粉丝
   */
  kTypeMutualFollowed(3),
  /**
   * 相互关注
   */
  kTypeBlack(4),
  /**
   * 黑名单
   */
  kTypeStranger(5),
  /**
   * 陌生人
   */
  kTypeFansBlack(6);

  private final int value;

  private FriendType(int value) {
    this.value = value;
  }

  @Override
  public int getValue() {
    return value;
  }
}
