// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\friend.proto
package com.wesocial.apollo.protocol.protobuf.friend;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;
import okio.ByteString;

import static com.squareup.wire.Message.Datatype.BYTES;
import static com.squareup.wire.Message.Datatype.INT32;
import static com.squareup.wire.Message.Datatype.INT64;
import static com.squareup.wire.Message.Datatype.UINT32;
import static com.squareup.wire.Message.Datatype.UINT64;

/**
 * 获取关注列表 (GET_FRIEND_LIST 406)
 */
public final class GetFriendListReq extends Message {
  private static final long serialVersionUID = 0L;

  public static final ByteString DEFAULT_RESERVED_BUF = ByteString.EMPTY;
  public static final Integer DEFAULT_FRIEND_TYPE = 0;
  public static final Long DEFAULT_VERSION = 0L;
  public static final Integer DEFAULT_GET_TYPE = 0;
  public static final Long DEFAULT_TIMESTAMP = 0L;
  public static final Integer DEFAULT_LIST_NUM = 0;

  @ProtoField(tag = 1, type = BYTES)
  public final ByteString reserved_buf;

  /**
   * 服务端使用，客户端忽略
   */
  @ProtoField(tag = 2, type = INT32)
  public final Integer friend_type;

  /**
   * kTypeFollowed / kTypeFans / kTypeMutualFollowed / kTypeBlack
   */
  @ProtoField(tag = 3, type = UINT64)
  public final Long version;

  /**
   * 当前的版本号
   */
  @ProtoField(tag = 4, type = INT32)
  public final Integer get_type;

  /**
   * 1 - 刷新 2 - 更多
   */
  @ProtoField(tag = 5, type = INT64)
  public final Long timestamp;

  /**
   * get_type = 2时有效 (<= timestamp, 毫秒级别)
   */
  @ProtoField(tag = 6, type = UINT32)
  public final Integer list_num;

  public GetFriendListReq(ByteString reserved_buf, Integer friend_type, Long version, Integer get_type, Long timestamp, Integer list_num) {
    this.reserved_buf = reserved_buf;
    this.friend_type = friend_type;
    this.version = version;
    this.get_type = get_type;
    this.timestamp = timestamp;
    this.list_num = list_num;
  }

  private GetFriendListReq(Builder builder) {
    this(builder.reserved_buf, builder.friend_type, builder.version, builder.get_type, builder.timestamp, builder.list_num);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof GetFriendListReq)) return false;
    GetFriendListReq o = (GetFriendListReq) other;
    return equals(reserved_buf, o.reserved_buf)
        && equals(friend_type, o.friend_type)
        && equals(version, o.version)
        && equals(get_type, o.get_type)
        && equals(timestamp, o.timestamp)
        && equals(list_num, o.list_num);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = reserved_buf != null ? reserved_buf.hashCode() : 0;
      result = result * 37 + (friend_type != null ? friend_type.hashCode() : 0);
      result = result * 37 + (version != null ? version.hashCode() : 0);
      result = result * 37 + (get_type != null ? get_type.hashCode() : 0);
      result = result * 37 + (timestamp != null ? timestamp.hashCode() : 0);
      result = result * 37 + (list_num != null ? list_num.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<GetFriendListReq> {

    public ByteString reserved_buf;
    public Integer friend_type;
    public Long version;
    public Integer get_type;
    public Long timestamp;
    public Integer list_num;

    public Builder() {
    }

    public Builder(GetFriendListReq message) {
      super(message);
      if (message == null) return;
      this.reserved_buf = message.reserved_buf;
      this.friend_type = message.friend_type;
      this.version = message.version;
      this.get_type = message.get_type;
      this.timestamp = message.timestamp;
      this.list_num = message.list_num;
    }

    public Builder reserved_buf(ByteString reserved_buf) {
      this.reserved_buf = reserved_buf;
      return this;
    }

    /**
     * 服务端使用，客户端忽略
     */
    public Builder friend_type(Integer friend_type) {
      this.friend_type = friend_type;
      return this;
    }

    /**
     * kTypeFollowed / kTypeFans / kTypeMutualFollowed / kTypeBlack
     */
    public Builder version(Long version) {
      this.version = version;
      return this;
    }

    /**
     * 当前的版本号
     */
    public Builder get_type(Integer get_type) {
      this.get_type = get_type;
      return this;
    }

    /**
     * 1 - 刷新 2 - 更多
     */
    public Builder timestamp(Long timestamp) {
      this.timestamp = timestamp;
      return this;
    }

    /**
     * get_type = 2时有效 (<= timestamp, 毫秒级别)
     */
    public Builder list_num(Integer list_num) {
      this.list_num = list_num;
      return this;
    }

    @Override
    public GetFriendListReq build() {
      return new GetFriendListReq(this);
    }
  }
}
