// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\friend.proto
package com.wesocial.apollo.protocol.protobuf.friend;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;
import java.util.Collections;
import java.util.List;
import okio.ByteString;

import static com.squareup.wire.Message.Datatype.BYTES;
import static com.squareup.wire.Message.Datatype.INT32;
import static com.squareup.wire.Message.Datatype.UINT32;
import static com.squareup.wire.Message.Datatype.UINT64;
import static com.squareup.wire.Message.Label.REPEATED;

public final class GetFriendListRsp extends Message {
  private static final long serialVersionUID = 0L;

  public static final ByteString DEFAULT_RESERVED_BUF = ByteString.EMPTY;
  public static final List<FriendInfo> DEFAULT_FRIENDS = Collections.emptyList();
  public static final Long DEFAULT_LATEST_VERSION = 0L;
  public static final Integer DEFAULT_TOTAL_NUM = 0;
  public static final Integer DEFAULT_IS_MORE = 0;

  @ProtoField(tag = 1, type = BYTES)
  public final ByteString reserved_buf;

  /**
   * 服务端使用，客户端忽略
   */
  @ProtoField(tag = 2, label = REPEATED, messageType = FriendInfo.class)
  public final List<FriendInfo> friends;

  /**
   *  好友信息
   */
  @ProtoField(tag = 3, type = UINT64)
  public final Long latest_version;

  /**
   * 当前version
   */
  @ProtoField(tag = 4, type = UINT32)
  public final Integer total_num;

  /**
   * 总数
   */
  @ProtoField(tag = 5, type = INT32)
  public final Integer is_more;

  public GetFriendListRsp(ByteString reserved_buf, List<FriendInfo> friends, Long latest_version, Integer total_num, Integer is_more) {
    this.reserved_buf = reserved_buf;
    this.friends = immutableCopyOf(friends);
    this.latest_version = latest_version;
    this.total_num = total_num;
    this.is_more = is_more;
  }

  private GetFriendListRsp(Builder builder) {
    this(builder.reserved_buf, builder.friends, builder.latest_version, builder.total_num, builder.is_more);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof GetFriendListRsp)) return false;
    GetFriendListRsp o = (GetFriendListRsp) other;
    return equals(reserved_buf, o.reserved_buf)
        && equals(friends, o.friends)
        && equals(latest_version, o.latest_version)
        && equals(total_num, o.total_num)
        && equals(is_more, o.is_more);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = reserved_buf != null ? reserved_buf.hashCode() : 0;
      result = result * 37 + (friends != null ? friends.hashCode() : 1);
      result = result * 37 + (latest_version != null ? latest_version.hashCode() : 0);
      result = result * 37 + (total_num != null ? total_num.hashCode() : 0);
      result = result * 37 + (is_more != null ? is_more.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<GetFriendListRsp> {

    public ByteString reserved_buf;
    public List<FriendInfo> friends;
    public Long latest_version;
    public Integer total_num;
    public Integer is_more;

    public Builder() {
    }

    public Builder(GetFriendListRsp message) {
      super(message);
      if (message == null) return;
      this.reserved_buf = message.reserved_buf;
      this.friends = copyOf(message.friends);
      this.latest_version = message.latest_version;
      this.total_num = message.total_num;
      this.is_more = message.is_more;
    }

    public Builder reserved_buf(ByteString reserved_buf) {
      this.reserved_buf = reserved_buf;
      return this;
    }

    /**
     * 服务端使用，客户端忽略
     */
    public Builder friends(List<FriendInfo> friends) {
      this.friends = checkForNulls(friends);
      return this;
    }

    /**
     *  好友信息
     */
    public Builder latest_version(Long latest_version) {
      this.latest_version = latest_version;
      return this;
    }

    /**
     * 当前version
     */
    public Builder total_num(Integer total_num) {
      this.total_num = total_num;
      return this;
    }

    /**
     * 总数
     */
    public Builder is_more(Integer is_more) {
      this.is_more = is_more;
      return this;
    }

    @Override
    public GetFriendListRsp build() {
      return new GetFriendListRsp(this);
    }
  }
}
