// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\friend.proto
package com.wesocial.apollo.protocol.protobuf.friend;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;
import java.util.Collections;
import java.util.List;
import okio.ByteString;

import static com.squareup.wire.Message.Datatype.BYTES;
import static com.squareup.wire.Message.Datatype.UINT64;
import static com.squareup.wire.Message.Label.REPEATED;

/**
 * 打招呼 (GREET_FRIEND 403)
 */
public final class GreetReq extends Message {
  private static final long serialVersionUID = 0L;

  public static final ByteString DEFAULT_RESERVED_BUF = ByteString.EMPTY;
  public static final List<Long> DEFAULT_GREET_INNER_IDS = Collections.emptyList();

  @ProtoField(tag = 1, type = BYTES)
  public final ByteString reserved_buf;

  /**
   * 服务端使用，客户端忽略
   */
  @ProtoField(tag = 2, type = UINT64, label = REPEATED)
  public final List<Long> greet_inner_ids;

  public GreetReq(ByteString reserved_buf, List<Long> greet_inner_ids) {
    this.reserved_buf = reserved_buf;
    this.greet_inner_ids = immutableCopyOf(greet_inner_ids);
  }

  private GreetReq(Builder builder) {
    this(builder.reserved_buf, builder.greet_inner_ids);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof GreetReq)) return false;
    GreetReq o = (GreetReq) other;
    return equals(reserved_buf, o.reserved_buf)
        && equals(greet_inner_ids, o.greet_inner_ids);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = reserved_buf != null ? reserved_buf.hashCode() : 0;
      result = result * 37 + (greet_inner_ids != null ? greet_inner_ids.hashCode() : 1);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<GreetReq> {

    public ByteString reserved_buf;
    public List<Long> greet_inner_ids;

    public Builder() {
    }

    public Builder(GreetReq message) {
      super(message);
      if (message == null) return;
      this.reserved_buf = message.reserved_buf;
      this.greet_inner_ids = copyOf(message.greet_inner_ids);
    }

    public Builder reserved_buf(ByteString reserved_buf) {
      this.reserved_buf = reserved_buf;
      return this;
    }

    /**
     * 服务端使用，客户端忽略
     */
    public Builder greet_inner_ids(List<Long> greet_inner_ids) {
      this.greet_inner_ids = checkForNulls(greet_inner_ids);
      return this;
    }

    @Override
    public GreetReq build() {
      return new GreetReq(this);
    }
  }
}
