// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\friend.proto
package com.wesocial.apollo.protocol.protobuf.friend;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;
import okio.ByteString;

import static com.squareup.wire.Message.Datatype.BYTES;
import static com.squareup.wire.Message.Datatype.UINT32;

public final class NewestGreetPersonRsp extends Message {
  private static final long serialVersionUID = 0L;

  public static final ByteString DEFAULT_RESERVED_BUF = ByteString.EMPTY;
  public static final Integer DEFAULT_TOTAL_NUM = 0;

  @ProtoField(tag = 1, type = BYTES)
  public final ByteString reserved_buf;

  /**
   * 服务端使用，客户端忽略
   */
  @ProtoField(tag = 2)
  public final FriendInfo friend_info;

  /**
   * 最新的打招呼信息
   */
  @ProtoField(tag = 3, type = UINT32)
  public final Integer total_num;

  public NewestGreetPersonRsp(ByteString reserved_buf, FriendInfo friend_info, Integer total_num) {
    this.reserved_buf = reserved_buf;
    this.friend_info = friend_info;
    this.total_num = total_num;
  }

  private NewestGreetPersonRsp(Builder builder) {
    this(builder.reserved_buf, builder.friend_info, builder.total_num);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof NewestGreetPersonRsp)) return false;
    NewestGreetPersonRsp o = (NewestGreetPersonRsp) other;
    return equals(reserved_buf, o.reserved_buf)
        && equals(friend_info, o.friend_info)
        && equals(total_num, o.total_num);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = reserved_buf != null ? reserved_buf.hashCode() : 0;
      result = result * 37 + (friend_info != null ? friend_info.hashCode() : 0);
      result = result * 37 + (total_num != null ? total_num.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<NewestGreetPersonRsp> {

    public ByteString reserved_buf;
    public FriendInfo friend_info;
    public Integer total_num;

    public Builder() {
    }

    public Builder(NewestGreetPersonRsp message) {
      super(message);
      if (message == null) return;
      this.reserved_buf = message.reserved_buf;
      this.friend_info = message.friend_info;
      this.total_num = message.total_num;
    }

    public Builder reserved_buf(ByteString reserved_buf) {
      this.reserved_buf = reserved_buf;
      return this;
    }

    /**
     * 服务端使用，客户端忽略
     */
    public Builder friend_info(FriendInfo friend_info) {
      this.friend_info = friend_info;
      return this;
    }

    /**
     * 最新的打招呼信息
     */
    public Builder total_num(Integer total_num) {
      this.total_num = total_num;
      return this;
    }

    @Override
    public NewestGreetPersonRsp build() {
      return new NewestGreetPersonRsp(this);
    }
  }
}
