// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\friend.proto
package com.wesocial.apollo.protocol.protobuf.friend;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;
import okio.ByteString;

import static com.squareup.wire.Message.Datatype.BYTES;
import static com.squareup.wire.Message.Datatype.UINT64;

/**
 * 取消黑名单 (REMOVE_BLACK 408)
 */
public final class RemoveBlackListReq extends Message {
  private static final long serialVersionUID = 0L;

  public static final ByteString DEFAULT_RESERVED_BUF = ByteString.EMPTY;
  public static final Long DEFAULT_FRIEND_ID = 0L;

  @ProtoField(tag = 1, type = BYTES)
  public final ByteString reserved_buf;

  /**
   * 服务端使用，客户端忽略
   */
  @ProtoField(tag = 2, type = UINT64)
  public final Long friend_id;

  public RemoveBlackListReq(ByteString reserved_buf, Long friend_id) {
    this.reserved_buf = reserved_buf;
    this.friend_id = friend_id;
  }

  private RemoveBlackListReq(Builder builder) {
    this(builder.reserved_buf, builder.friend_id);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof RemoveBlackListReq)) return false;
    RemoveBlackListReq o = (RemoveBlackListReq) other;
    return equals(reserved_buf, o.reserved_buf)
        && equals(friend_id, o.friend_id);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = reserved_buf != null ? reserved_buf.hashCode() : 0;
      result = result * 37 + (friend_id != null ? friend_id.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<RemoveBlackListReq> {

    public ByteString reserved_buf;
    public Long friend_id;

    public Builder() {
    }

    public Builder(RemoveBlackListReq message) {
      super(message);
      if (message == null) return;
      this.reserved_buf = message.reserved_buf;
      this.friend_id = message.friend_id;
    }

    public Builder reserved_buf(ByteString reserved_buf) {
      this.reserved_buf = reserved_buf;
      return this;
    }

    /**
     * 服务端使用，客户端忽略
     */
    public Builder friend_id(Long friend_id) {
      this.friend_id = friend_id;
      return this;
    }

    @Override
    public RemoveBlackListReq build() {
      return new RemoveBlackListReq(this);
    }
  }
}
