// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\friend.proto
package com.wesocial.apollo.protocol.protobuf.friend;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;
import okio.ByteString;

import static com.squareup.wire.Message.Datatype.BYTES;
import static com.squareup.wire.Message.Datatype.UINT64;

/**
 * 取消关注 (UNFOLLOW_FRIEND 402)
 */
public final class UnFollowReq extends Message {
  private static final long serialVersionUID = 0L;

  public static final ByteString DEFAULT_RESERVED_BUF = ByteString.EMPTY;
  public static final Long DEFAULT_UNFOLLOW_INNER_ID = 0L;

  @ProtoField(tag = 1, type = BYTES)
  public final ByteString reserved_buf;

  /**
   * 服务端使用，客户端忽略
   */
  @ProtoField(tag = 2, type = UINT64)
  public final Long unfollow_inner_id;

  public UnFollowReq(ByteString reserved_buf, Long unfollow_inner_id) {
    this.reserved_buf = reserved_buf;
    this.unfollow_inner_id = unfollow_inner_id;
  }

  private UnFollowReq(Builder builder) {
    this(builder.reserved_buf, builder.unfollow_inner_id);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof UnFollowReq)) return false;
    UnFollowReq o = (UnFollowReq) other;
    return equals(reserved_buf, o.reserved_buf)
        && equals(unfollow_inner_id, o.unfollow_inner_id);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = reserved_buf != null ? reserved_buf.hashCode() : 0;
      result = result * 37 + (unfollow_inner_id != null ? unfollow_inner_id.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<UnFollowReq> {

    public ByteString reserved_buf;
    public Long unfollow_inner_id;

    public Builder() {
    }

    public Builder(UnFollowReq message) {
      super(message);
      if (message == null) return;
      this.reserved_buf = message.reserved_buf;
      this.unfollow_inner_id = message.unfollow_inner_id;
    }

    public Builder reserved_buf(ByteString reserved_buf) {
      this.reserved_buf = reserved_buf;
      return this;
    }

    /**
     * 服务端使用，客户端忽略
     */
    public Builder unfollow_inner_id(Long unfollow_inner_id) {
      this.unfollow_inner_id = unfollow_inner_id;
      return this;
    }

    @Override
    public UnFollowReq build() {
      return new UnFollowReq(this);
    }
  }
}
