// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\lbs.proto
package com.wesocial.apollo.protocol.protobuf.lbs;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;
import java.util.Collections;
import java.util.List;
import okio.ByteString;

import static com.squareup.wire.Message.Datatype.BYTES;
import static com.squareup.wire.Message.Datatype.UINT32;
import static com.squareup.wire.Message.Label.REPEATED;

public final class EncounterRsp extends Message {
  private static final long serialVersionUID = 0L;

  public static final ByteString DEFAULT_RESERVED_BUF = ByteString.EMPTY;
  public static final List<PersonInfo> DEFAULT_LIST_INFOS = Collections.emptyList();
  public static final Integer DEFAULT_TOTAL_NUM = 0;
  public static final Integer DEFAULT_IS_END = 0;

  @ProtoField(tag = 1, type = BYTES)
  public final ByteString reserved_buf;

  /**
   * 服务端使用，客户端忽略
   */
  @ProtoField(tag = 2, label = REPEATED, messageType = PersonInfo.class)
  public final List<PersonInfo> list_infos;

  @ProtoField(tag = 3, type = UINT32)
  public final Integer total_num;

  @ProtoField(tag = 4, type = UINT32)
  public final Integer is_end;

  public EncounterRsp(ByteString reserved_buf, List<PersonInfo> list_infos, Integer total_num, Integer is_end) {
    this.reserved_buf = reserved_buf;
    this.list_infos = immutableCopyOf(list_infos);
    this.total_num = total_num;
    this.is_end = is_end;
  }

  private EncounterRsp(Builder builder) {
    this(builder.reserved_buf, builder.list_infos, builder.total_num, builder.is_end);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof EncounterRsp)) return false;
    EncounterRsp o = (EncounterRsp) other;
    return equals(reserved_buf, o.reserved_buf)
        && equals(list_infos, o.list_infos)
        && equals(total_num, o.total_num)
        && equals(is_end, o.is_end);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = reserved_buf != null ? reserved_buf.hashCode() : 0;
      result = result * 37 + (list_infos != null ? list_infos.hashCode() : 1);
      result = result * 37 + (total_num != null ? total_num.hashCode() : 0);
      result = result * 37 + (is_end != null ? is_end.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<EncounterRsp> {

    public ByteString reserved_buf;
    public List<PersonInfo> list_infos;
    public Integer total_num;
    public Integer is_end;

    public Builder() {
    }

    public Builder(EncounterRsp message) {
      super(message);
      if (message == null) return;
      this.reserved_buf = message.reserved_buf;
      this.list_infos = copyOf(message.list_infos);
      this.total_num = message.total_num;
      this.is_end = message.is_end;
    }

    public Builder reserved_buf(ByteString reserved_buf) {
      this.reserved_buf = reserved_buf;
      return this;
    }

    /**
     * 服务端使用，客户端忽略
     */
    public Builder list_infos(List<PersonInfo> list_infos) {
      this.list_infos = checkForNulls(list_infos);
      return this;
    }

    public Builder total_num(Integer total_num) {
      this.total_num = total_num;
      return this;
    }

    public Builder is_end(Integer is_end) {
      this.is_end = is_end;
      return this;
    }

    @Override
    public EncounterRsp build() {
      return new EncounterRsp(this);
    }
  }
}
