// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\lbs.proto
package com.wesocial.apollo.protocol.protobuf.lbs;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;
import okio.ByteString;

import static com.squareup.wire.Message.Datatype.BYTES;
import static com.squareup.wire.Message.Datatype.INT32;
import static com.squareup.wire.Message.Datatype.INT64;
import static com.squareup.wire.Message.Datatype.UINT32;

/**
 * ////////////////////////////////////////////////////////////////////////////
 * 全民偶遇
 * cmd = ENCOUNTER_ALL
 */
public final class EncounterReq extends Message {
  private static final long serialVersionUID = 0L;

  public static final ByteString DEFAULT_RESERVED_BUF = ByteString.EMPTY;
  public static final Integer DEFAULT_TYPE = 0;
  public static final Long DEFAULT_TIMESTAMP = 0L;
  public static final Integer DEFAULT_SEX = 0;
  public static final Integer DEFAULT_REQ_NUM = 0;

  @ProtoField(tag = 1, type = BYTES)
  public final ByteString reserved_buf;

  /**
   * 服务端使用，客户端忽略
   */
  @ProtoField(tag = 2, type = INT32)
  public final Integer type;

  /**
   * 1 - 强制刷新 2 - 更多 3 - 下拉刷新
   */
  @ProtoField(tag = 3, type = INT64)
  public final Long timestamp;

  /**
   * type=2时: <= timestamp; type=3时：>= timestamp（毫秒级别, 客户端需要排重）
   */
  @ProtoField(tag = 4, type = INT32)
  public final Integer sex;

  /**
   * 性别 1 - 男 2 - 女 3 - 不区分
   */
  @ProtoField(tag = 5, type = UINT32)
  public final Integer req_num;

  public EncounterReq(ByteString reserved_buf, Integer type, Long timestamp, Integer sex, Integer req_num) {
    this.reserved_buf = reserved_buf;
    this.type = type;
    this.timestamp = timestamp;
    this.sex = sex;
    this.req_num = req_num;
  }

  private EncounterReq(Builder builder) {
    this(builder.reserved_buf, builder.type, builder.timestamp, builder.sex, builder.req_num);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof EncounterReq)) return false;
    EncounterReq o = (EncounterReq) other;
    return equals(reserved_buf, o.reserved_buf)
        && equals(type, o.type)
        && equals(timestamp, o.timestamp)
        && equals(sex, o.sex)
        && equals(req_num, o.req_num);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = reserved_buf != null ? reserved_buf.hashCode() : 0;
      result = result * 37 + (type != null ? type.hashCode() : 0);
      result = result * 37 + (timestamp != null ? timestamp.hashCode() : 0);
      result = result * 37 + (sex != null ? sex.hashCode() : 0);
      result = result * 37 + (req_num != null ? req_num.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<EncounterReq> {

    public ByteString reserved_buf;
    public Integer type;
    public Long timestamp;
    public Integer sex;
    public Integer req_num;

    public Builder() {
    }

    public Builder(EncounterReq message) {
      super(message);
      if (message == null) return;
      this.reserved_buf = message.reserved_buf;
      this.type = message.type;
      this.timestamp = message.timestamp;
      this.sex = message.sex;
      this.req_num = message.req_num;
    }

    public Builder reserved_buf(ByteString reserved_buf) {
      this.reserved_buf = reserved_buf;
      return this;
    }

    /**
     * 服务端使用，客户端忽略
     */
    public Builder type(Integer type) {
      this.type = type;
      return this;
    }

    /**
     * 1 - 强制刷新 2 - 更多 3 - 下拉刷新
     */
    public Builder timestamp(Long timestamp) {
      this.timestamp = timestamp;
      return this;
    }

    /**
     * type=2时: <= timestamp; type=3时：>= timestamp（毫秒级别, 客户端需要排重）
     */
    public Builder sex(Integer sex) {
      this.sex = sex;
      return this;
    }

    /**
     * 性别 1 - 男 2 - 女 3 - 不区分
     */
    public Builder req_num(Integer req_num) {
      this.req_num = req_num;
      return this;
    }

    @Override
    public EncounterReq build() {
      return new EncounterReq(this);
    }
  }
}
