// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\lbs.proto
package com.wesocial.apollo.protocol.protobuf.lbs;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;
import okio.ByteString;

import static com.squareup.wire.Message.Datatype.BYTES;
import static com.squareup.wire.Message.Datatype.DOUBLE;

/**
 * ////////////////////////////////////////////////////////////////////////////
 * 获取LBS对应的城市信息（该接口已废弃）
 * cmd = GET_CITY_ID
 */
public final class GetCityIdReq extends Message {
  private static final long serialVersionUID = 0L;

  public static final ByteString DEFAULT_RESERVED_BUF = ByteString.EMPTY;
  public static final Double DEFAULT_LATITUDE = 0D;
  public static final Double DEFAULT_LONGITUDE = 0D;

  @ProtoField(tag = 1, type = BYTES)
  public final ByteString reserved_buf;

  /**
   * 服务端使用，客户端忽略
   */
  @ProtoField(tag = 2, type = DOUBLE)
  public final Double latitude;

  /**
   * 纬度
   */
  @ProtoField(tag = 3, type = DOUBLE)
  public final Double longitude;

  public GetCityIdReq(ByteString reserved_buf, Double latitude, Double longitude) {
    this.reserved_buf = reserved_buf;
    this.latitude = latitude;
    this.longitude = longitude;
  }

  private GetCityIdReq(Builder builder) {
    this(builder.reserved_buf, builder.latitude, builder.longitude);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof GetCityIdReq)) return false;
    GetCityIdReq o = (GetCityIdReq) other;
    return equals(reserved_buf, o.reserved_buf)
        && equals(latitude, o.latitude)
        && equals(longitude, o.longitude);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = reserved_buf != null ? reserved_buf.hashCode() : 0;
      result = result * 37 + (latitude != null ? latitude.hashCode() : 0);
      result = result * 37 + (longitude != null ? longitude.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<GetCityIdReq> {

    public ByteString reserved_buf;
    public Double latitude;
    public Double longitude;

    public Builder() {
    }

    public Builder(GetCityIdReq message) {
      super(message);
      if (message == null) return;
      this.reserved_buf = message.reserved_buf;
      this.latitude = message.latitude;
      this.longitude = message.longitude;
    }

    public Builder reserved_buf(ByteString reserved_buf) {
      this.reserved_buf = reserved_buf;
      return this;
    }

    /**
     * 服务端使用，客户端忽略
     */
    public Builder latitude(Double latitude) {
      this.latitude = latitude;
      return this;
    }

    /**
     * 纬度
     */
    public Builder longitude(Double longitude) {
      this.longitude = longitude;
      return this;
    }

    @Override
    public GetCityIdReq build() {
      return new GetCityIdReq(this);
    }
  }
}
