// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\lbs.proto
package com.wesocial.apollo.protocol.protobuf.lbs;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.FLOAT;
import static com.squareup.wire.Message.Datatype.INT64;
import static com.squareup.wire.Message.Datatype.UINT64;

public final class LbsPersonInfo extends Message {
  private static final long serialVersionUID = 0L;

  public static final Long DEFAULT_INNER_ID = 0L;
  public static final Long DEFAULT_TIMESTAMP = 0L;
  public static final Float DEFAULT_DISTANCE = 0F;

  @ProtoField(tag = 1, type = UINT64)
  public final Long inner_id;

  /**
   * inner_id
   */
  @ProtoField(tag = 2, type = INT64)
  public final Long timestamp;

  /**
   * 时间
   */
  @ProtoField(tag = 3, type = FLOAT)
  public final Float distance;

  public LbsPersonInfo(Long inner_id, Long timestamp, Float distance) {
    this.inner_id = inner_id;
    this.timestamp = timestamp;
    this.distance = distance;
  }

  private LbsPersonInfo(Builder builder) {
    this(builder.inner_id, builder.timestamp, builder.distance);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof LbsPersonInfo)) return false;
    LbsPersonInfo o = (LbsPersonInfo) other;
    return equals(inner_id, o.inner_id)
        && equals(timestamp, o.timestamp)
        && equals(distance, o.distance);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = inner_id != null ? inner_id.hashCode() : 0;
      result = result * 37 + (timestamp != null ? timestamp.hashCode() : 0);
      result = result * 37 + (distance != null ? distance.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<LbsPersonInfo> {

    public Long inner_id;
    public Long timestamp;
    public Float distance;

    public Builder() {
    }

    public Builder(LbsPersonInfo message) {
      super(message);
      if (message == null) return;
      this.inner_id = message.inner_id;
      this.timestamp = message.timestamp;
      this.distance = message.distance;
    }

    public Builder inner_id(Long inner_id) {
      this.inner_id = inner_id;
      return this;
    }

    /**
     * inner_id
     */
    public Builder timestamp(Long timestamp) {
      this.timestamp = timestamp;
      return this;
    }

    /**
     * 时间
     */
    public Builder distance(Float distance) {
      this.distance = distance;
      return this;
    }

    @Override
    public LbsPersonInfo build() {
      return new LbsPersonInfo(this);
    }
  }
}
