// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\lbs.proto
package com.wesocial.apollo.protocol.protobuf.lbs;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;
import java.util.Collections;
import java.util.List;
import okio.ByteString;

import static com.squareup.wire.Message.Datatype.BYTES;
import static com.squareup.wire.Message.Label.REPEATED;

public final class NearbyPersonRsp extends Message {
  private static final long serialVersionUID = 0L;

  public static final ByteString DEFAULT_RESERVED_BUF = ByteString.EMPTY;
  public static final List<LbsPersonInfo> DEFAULT_LIST_INFOS = Collections.emptyList();

  @ProtoField(tag = 1, type = BYTES)
  public final ByteString reserved_buf;

  /**
   * 服务端使用，客户端忽略
   */
  @ProtoField(tag = 2, label = REPEATED, messageType = LbsPersonInfo.class)
  public final List<LbsPersonInfo> list_infos;

  public NearbyPersonRsp(ByteString reserved_buf, List<LbsPersonInfo> list_infos) {
    this.reserved_buf = reserved_buf;
    this.list_infos = immutableCopyOf(list_infos);
  }

  private NearbyPersonRsp(Builder builder) {
    this(builder.reserved_buf, builder.list_infos);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof NearbyPersonRsp)) return false;
    NearbyPersonRsp o = (NearbyPersonRsp) other;
    return equals(reserved_buf, o.reserved_buf)
        && equals(list_infos, o.list_infos);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = reserved_buf != null ? reserved_buf.hashCode() : 0;
      result = result * 37 + (list_infos != null ? list_infos.hashCode() : 1);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<NearbyPersonRsp> {

    public ByteString reserved_buf;
    public List<LbsPersonInfo> list_infos;

    public Builder() {
    }

    public Builder(NearbyPersonRsp message) {
      super(message);
      if (message == null) return;
      this.reserved_buf = message.reserved_buf;
      this.list_infos = copyOf(message.list_infos);
    }

    public Builder reserved_buf(ByteString reserved_buf) {
      this.reserved_buf = reserved_buf;
      return this;
    }

    /**
     * 服务端使用，客户端忽略
     */
    public Builder list_infos(List<LbsPersonInfo> list_infos) {
      this.list_infos = checkForNulls(list_infos);
      return this;
    }

    @Override
    public NearbyPersonRsp build() {
      return new NearbyPersonRsp(this);
    }
  }
}
