// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\message.proto
package com.wesocial.apollo.protocol.protobuf.message;

import com.squareup.wire.ProtoEnum;

public enum MessageType
    implements ProtoEnum {
  kMessageUser(1),
  /**
   * 用户消息
   */
  kMessageSystem(2),
  /**
   * 系统消息
   */
  kMessageImage(3),
  /**
   * 图片
   */
  kMessageVoice(4),
  /**
   * 语音
   */
  kMessageMedia(5),
  /**
   * 多媒体
   */
  kMessageFlower(6),
  /**
   * 送花消息
   */
  kMessageTmpImage(7),
  /**
   * 阅后即焚图片消息
   */
  kMessageTruthOrBrave(8),
  /**
   * 真心话大冒险
   */
  kMessageGameReport(9);

  private final int value;

  private MessageType(int value) {
    this.value = value;
  }

  @Override
  public int getValue() {
    return value;
  }
}
