// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\message.proto
package com.wesocial.apollo.protocol.protobuf.message;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;
import java.util.Collections;
import java.util.List;
import okio.ByteString;

import static com.squareup.wire.Message.Datatype.BYTES;
import static com.squareup.wire.Message.Datatype.UINT64;
import static com.squareup.wire.Message.Label.REPEATED;

public final class RecvNewMessageRsp extends Message {
  private static final long serialVersionUID = 0L;

  public static final ByteString DEFAULT_RESERVED_BUF = ByteString.EMPTY;
  public static final List<MessageRecord> DEFAULT_MESSAGE_RECORD = Collections.emptyList();
  public static final Long DEFAULT_SERVER_MAX_ID = 0L;

  @ProtoField(tag = 1, type = BYTES)
  public final ByteString reserved_buf;

  /**
   * 服务端使用，客户端忽略
   */
  @ProtoField(tag = 2, label = REPEATED, messageType = MessageRecord.class)
  public final List<MessageRecord> message_record;

  /**
   * 所有新消息记录
   */
  @ProtoField(tag = 3, type = UINT64)
  public final Long server_max_id;

  public RecvNewMessageRsp(ByteString reserved_buf, List<MessageRecord> message_record, Long server_max_id) {
    this.reserved_buf = reserved_buf;
    this.message_record = immutableCopyOf(message_record);
    this.server_max_id = server_max_id;
  }

  private RecvNewMessageRsp(Builder builder) {
    this(builder.reserved_buf, builder.message_record, builder.server_max_id);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof RecvNewMessageRsp)) return false;
    RecvNewMessageRsp o = (RecvNewMessageRsp) other;
    return equals(reserved_buf, o.reserved_buf)
        && equals(message_record, o.message_record)
        && equals(server_max_id, o.server_max_id);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = reserved_buf != null ? reserved_buf.hashCode() : 0;
      result = result * 37 + (message_record != null ? message_record.hashCode() : 1);
      result = result * 37 + (server_max_id != null ? server_max_id.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<RecvNewMessageRsp> {

    public ByteString reserved_buf;
    public List<MessageRecord> message_record;
    public Long server_max_id;

    public Builder() {
    }

    public Builder(RecvNewMessageRsp message) {
      super(message);
      if (message == null) return;
      this.reserved_buf = message.reserved_buf;
      this.message_record = copyOf(message.message_record);
      this.server_max_id = message.server_max_id;
    }

    public Builder reserved_buf(ByteString reserved_buf) {
      this.reserved_buf = reserved_buf;
      return this;
    }

    /**
     * 服务端使用，客户端忽略
     */
    public Builder message_record(List<MessageRecord> message_record) {
      this.message_record = checkForNulls(message_record);
      return this;
    }

    /**
     * 所有新消息记录
     */
    public Builder server_max_id(Long server_max_id) {
      this.server_max_id = server_max_id;
      return this;
    }

    @Override
    public RecvNewMessageRsp build() {
      return new RecvNewMessageRsp(this);
    }
  }
}
