// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\message.proto
package com.wesocial.apollo.protocol.protobuf.message;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;
import okio.ByteString;

import static com.squareup.wire.Message.Datatype.BYTES;
import static com.squareup.wire.Message.Datatype.UINT64;

/**
 * II. 获取新消息
 * CMD为RECV_NEW_MESSAGE（502），请求结构为RecvNewMessageReq，返回结构为RecvNewMessageRsp
 */
public final class RecvNewMessageReq extends Message {
  private static final long serialVersionUID = 0L;

  public static final ByteString DEFAULT_RESERVED_BUF = ByteString.EMPTY;
  public static final Long DEFAULT_CLIENT_MAX_ID = 0L;

  @ProtoField(tag = 1, type = BYTES)
  public final ByteString reserved_buf;

  /**
   * 服务端使用，客户端忽略
   */
  @ProtoField(tag = 3, type = UINT64)
  public final Long client_max_id;

  public RecvNewMessageReq(ByteString reserved_buf, Long client_max_id) {
    this.reserved_buf = reserved_buf;
    this.client_max_id = client_max_id;
  }

  private RecvNewMessageReq(Builder builder) {
    this(builder.reserved_buf, builder.client_max_id);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof RecvNewMessageReq)) return false;
    RecvNewMessageReq o = (RecvNewMessageReq) other;
    return equals(reserved_buf, o.reserved_buf)
        && equals(client_max_id, o.client_max_id);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = reserved_buf != null ? reserved_buf.hashCode() : 0;
      result = result * 37 + (client_max_id != null ? client_max_id.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<RecvNewMessageReq> {

    public ByteString reserved_buf;
    public Long client_max_id;

    public Builder() {
    }

    public Builder(RecvNewMessageReq message) {
      super(message);
      if (message == null) return;
      this.reserved_buf = message.reserved_buf;
      this.client_max_id = message.client_max_id;
    }

    public Builder reserved_buf(ByteString reserved_buf) {
      this.reserved_buf = reserved_buf;
      return this;
    }

    /**
     * 服务端使用，客户端忽略
     */
    public Builder client_max_id(Long client_max_id) {
      this.client_max_id = client_max_id;
      return this;
    }

    @Override
    public RecvNewMessageReq build() {
      return new RecvNewMessageReq(this);
    }
  }
}
