// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\pvpmatch.proto
package com.wesocial.apollo.protocol.protobuf.pvpmatch;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.INT32;
import static com.squareup.wire.Message.Datatype.UINT64;

public final class OnlineUserInfo extends Message {
  private static final long serialVersionUID = 0L;

  public static final Long DEFAULT_INNER_ID = 0L;
  public static final Integer DEFAULT_USER_STATUS = 0;

  @ProtoField(tag = 1, type = UINT64)
  public final Long inner_id;

  /**
   * 用户id
   */
  @ProtoField(tag = 7, type = INT32)
  public final Integer user_status;

  public OnlineUserInfo(Long inner_id, Integer user_status) {
    this.inner_id = inner_id;
    this.user_status = user_status;
  }

  private OnlineUserInfo(Builder builder) {
    this(builder.inner_id, builder.user_status);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof OnlineUserInfo)) return false;
    OnlineUserInfo o = (OnlineUserInfo) other;
    return equals(inner_id, o.inner_id)
        && equals(user_status, o.user_status);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = inner_id != null ? inner_id.hashCode() : 0;
      result = result * 37 + (user_status != null ? user_status.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<OnlineUserInfo> {

    public Long inner_id;
    public Integer user_status;

    public Builder() {
    }

    public Builder(OnlineUserInfo message) {
      super(message);
      if (message == null) return;
      this.inner_id = message.inner_id;
      this.user_status = message.user_status;
    }

    public Builder inner_id(Long inner_id) {
      this.inner_id = inner_id;
      return this;
    }

    /**
     * 用户id
     */
    public Builder user_status(Integer user_status) {
      this.user_status = user_status;
      return this;
    }

    @Override
    public OnlineUserInfo build() {
      return new OnlineUserInfo(this);
    }
  }
}
