// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\pvpmatch.proto
package com.wesocial.apollo.protocol.protobuf.pvpmatch;

import com.squareup.wire.ProtoEnum;

public enum PvpMatch_MatchResult
    implements ProtoEnum {
  kMatchAcceptOk(1),
  /**
   * 接受匹配请求
   */
  kMatchAcceptFail(2),
  /**
   * 拒绝匹配请求 玩家已经在游戏中
   */
  kMatchAlreadyMathing(3);

  private final int value;

  private PvpMatch_MatchResult(int value) {
    this.value = value;
  }

  @Override
  public int getValue() {
    return value;
  }
}
