// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\pvpmatch.proto
package com.wesocial.apollo.protocol.protobuf.pvpmatch;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;
import java.util.Collections;
import java.util.List;

import static com.squareup.wire.Message.Label.REPEATED;

public final class PvpMatch_GameInfoList extends Message {
  private static final long serialVersionUID = 0L;

  public static final List<PvpMatch_GameInfo> DEFAULT_GAME_INFO = Collections.emptyList();

  @ProtoField(tag = 1, label = REPEATED, messageType = PvpMatch_GameInfo.class)
  public final List<PvpMatch_GameInfo> game_info;

  public PvpMatch_GameInfoList(List<PvpMatch_GameInfo> game_info) {
    this.game_info = immutableCopyOf(game_info);
  }

  private PvpMatch_GameInfoList(Builder builder) {
    this(builder.game_info);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof PvpMatch_GameInfoList)) return false;
    return equals(game_info, ((PvpMatch_GameInfoList) other).game_info);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    return result != 0 ? result : (hashCode = game_info != null ? game_info.hashCode() : 1);
  }

  public static final class Builder extends Message.Builder<PvpMatch_GameInfoList> {

    public List<PvpMatch_GameInfo> game_info;

    public Builder() {
    }

    public Builder(PvpMatch_GameInfoList message) {
      super(message);
      if (message == null) return;
      this.game_info = copyOf(message.game_info);
    }

    public Builder game_info(List<PvpMatch_GameInfo> game_info) {
      this.game_info = checkForNulls(game_info);
      return this;
    }

    @Override
    public PvpMatch_GameInfoList build() {
      return new PvpMatch_GameInfoList(this);
    }
  }
}
