// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\pay.proto
package com.wesocial.apollo.protocol.protobuf.pay;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;
import okio.ByteString;

import static com.squareup.wire.Message.Datatype.BYTES;
import static com.squareup.wire.Message.Datatype.UINT32;
import static com.squareup.wire.Message.Datatype.UINT64;

public final class GiveGiftReq extends Message {
  private static final long serialVersionUID = 0L;

  public static final ByteString DEFAULT_RESERVED_BUF = ByteString.EMPTY;
  public static final Long DEFAULT_TO_INNER_ID = 0L;
  public static final Long DEFAULT_GIFT_ID = 0L;
  public static final Integer DEFAULT_GIFT_NUM = 0;
  public static final Long DEFAULT_TID = 0L;
  public static final Long DEFAULT_BILLNO = 0L;

  @ProtoField(tag = 1, type = BYTES)
  public final ByteString reserved_buf;

  /**
   * 服务端使用，客户端忽略
   */
  @ProtoField(tag = 2, type = UINT64)
  public final Long to_inner_id;

  @ProtoField(tag = 3, type = UINT64)
  public final Long gift_id;

  @ProtoField(tag = 4, type = UINT32)
  public final Integer gift_num;

  @ProtoField(tag = 5, type = UINT64)
  public final Long tid;

  @ProtoField(tag = 6, type = UINT64)
  public final Long billno;

  public GiveGiftReq(ByteString reserved_buf, Long to_inner_id, Long gift_id, Integer gift_num, Long tid, Long billno) {
    this.reserved_buf = reserved_buf;
    this.to_inner_id = to_inner_id;
    this.gift_id = gift_id;
    this.gift_num = gift_num;
    this.tid = tid;
    this.billno = billno;
  }

  private GiveGiftReq(Builder builder) {
    this(builder.reserved_buf, builder.to_inner_id, builder.gift_id, builder.gift_num, builder.tid, builder.billno);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof GiveGiftReq)) return false;
    GiveGiftReq o = (GiveGiftReq) other;
    return equals(reserved_buf, o.reserved_buf)
        && equals(to_inner_id, o.to_inner_id)
        && equals(gift_id, o.gift_id)
        && equals(gift_num, o.gift_num)
        && equals(tid, o.tid)
        && equals(billno, o.billno);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = reserved_buf != null ? reserved_buf.hashCode() : 0;
      result = result * 37 + (to_inner_id != null ? to_inner_id.hashCode() : 0);
      result = result * 37 + (gift_id != null ? gift_id.hashCode() : 0);
      result = result * 37 + (gift_num != null ? gift_num.hashCode() : 0);
      result = result * 37 + (tid != null ? tid.hashCode() : 0);
      result = result * 37 + (billno != null ? billno.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<GiveGiftReq> {

    public ByteString reserved_buf;
    public Long to_inner_id;
    public Long gift_id;
    public Integer gift_num;
    public Long tid;
    public Long billno;

    public Builder() {
    }

    public Builder(GiveGiftReq message) {
      super(message);
      if (message == null) return;
      this.reserved_buf = message.reserved_buf;
      this.to_inner_id = message.to_inner_id;
      this.gift_id = message.gift_id;
      this.gift_num = message.gift_num;
      this.tid = message.tid;
      this.billno = message.billno;
    }

    public Builder reserved_buf(ByteString reserved_buf) {
      this.reserved_buf = reserved_buf;
      return this;
    }

    /**
     * 服务端使用，客户端忽略
     */
    public Builder to_inner_id(Long to_inner_id) {
      this.to_inner_id = to_inner_id;
      return this;
    }

    public Builder gift_id(Long gift_id) {
      this.gift_id = gift_id;
      return this;
    }

    public Builder gift_num(Integer gift_num) {
      this.gift_num = gift_num;
      return this;
    }

    public Builder tid(Long tid) {
      this.tid = tid;
      return this;
    }

    public Builder billno(Long billno) {
      this.billno = billno;
      return this;
    }

    @Override
    public GiveGiftReq build() {
      return new GiveGiftReq(this);
    }
  }
}
