// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\game_pktown.proto
package com.wesocial.apollo.protocol.protobuf.game_pktown;

import com.squareup.wire.ProtoEnum;

public enum GamePktownPlayerStatus
    implements ProtoEnum {
  GAME_PKTOWN_PLAYER_STATUS_NONE(1),
  /**
   * 用户不存在
   */
  GAME_PKTOWN_PLAYER_STATUS_PLAYING(2),
  /**
   * 游戏中
   */
  GAME_PKTOWN_PLAYER_STATUS_GAME_OVER(3);

  private final int value;

  private GamePktownPlayerStatus(int value) {
    this.value = value;
  }

  @Override
  public int getValue() {
    return value;
  }
}
