// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\game_pktown.proto
package com.wesocial.apollo.protocol.protobuf.game_pktown;

import com.squareup.wire.ProtoEnum;

public enum GamePktownCmdType
    implements ProtoEnum {
  GAME_PKTOWN_CMD_TYPE_UPDATE_SCORE(1),
  /**
   * 上报游戏分数
   */
  GAME_PKTOWN_CMD_TYPE_GAME_OVER(2);

  private final int value;

  private GamePktownCmdType(int value) {
    this.value = value;
  }

  @Override
  public int getValue() {
    return value;
  }
}
