// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\game_pktown.proto
package com.wesocial.apollo.protocol.protobuf.game_pktown;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;
import com.wesocial.apollo.protocol.protobuf.game.GameResult;
import com.wesocial.apollo.protocol.protobuf.game.RouteInfo;
import java.util.Collections;
import java.util.List;

import static com.squareup.wire.Message.Datatype.INT32;
import static com.squareup.wire.Message.Datatype.STRING;
import static com.squareup.wire.Message.Label.REPEATED;

/**
 * pk场游戏结果推送
 */
public final class GamePktownGameResult extends Message {
  private static final long serialVersionUID = 0L;

  public static final String DEFAULT_GAME_NAME = "";
  public static final String DEFAULT_ICON_URL = "";
  public static final Integer DEFAULT_GAME_POLICY = 0;
  public static final List<GamePktownPlayerData> DEFAULT_PLAYER_DATAS = Collections.emptyList();
  public static final String DEFAULT_GAME_JUMP_URL = "";

  @ProtoField(tag = 1)
  public final RouteInfo route_info;

  /**
   * 路由信息
   */
  @ProtoField(tag = 2, type = STRING)
  public final String game_name;

  /**
   * 游戏名
   */
  @ProtoField(tag = 3, type = STRING)
  public final String icon_url;

  /**
   * 游戏图标
   */
  @ProtoField(tag = 4, type = INT32)
  public final Integer game_policy;

  /**
   * 游戏策略
   */
  @ProtoField(tag = 5, label = REPEATED, messageType = GamePktownPlayerData.class)
  public final List<GamePktownPlayerData> player_datas;

  /**
   * 每个玩家的结果
   */
  @ProtoField(tag = 6, type = STRING)
  public final String game_jump_url;

  /**
   * 游戏跳转url
   */
  @ProtoField(tag = 7)
  public final GameResult game_result;

  public GamePktownGameResult(RouteInfo route_info, String game_name, String icon_url, Integer game_policy, List<GamePktownPlayerData> player_datas, String game_jump_url, GameResult game_result) {
    this.route_info = route_info;
    this.game_name = game_name;
    this.icon_url = icon_url;
    this.game_policy = game_policy;
    this.player_datas = immutableCopyOf(player_datas);
    this.game_jump_url = game_jump_url;
    this.game_result = game_result;
  }

  private GamePktownGameResult(Builder builder) {
    this(builder.route_info, builder.game_name, builder.icon_url, builder.game_policy, builder.player_datas, builder.game_jump_url, builder.game_result);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof GamePktownGameResult)) return false;
    GamePktownGameResult o = (GamePktownGameResult) other;
    return equals(route_info, o.route_info)
        && equals(game_name, o.game_name)
        && equals(icon_url, o.icon_url)
        && equals(game_policy, o.game_policy)
        && equals(player_datas, o.player_datas)
        && equals(game_jump_url, o.game_jump_url)
        && equals(game_result, o.game_result);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = route_info != null ? route_info.hashCode() : 0;
      result = result * 37 + (game_name != null ? game_name.hashCode() : 0);
      result = result * 37 + (icon_url != null ? icon_url.hashCode() : 0);
      result = result * 37 + (game_policy != null ? game_policy.hashCode() : 0);
      result = result * 37 + (player_datas != null ? player_datas.hashCode() : 1);
      result = result * 37 + (game_jump_url != null ? game_jump_url.hashCode() : 0);
      result = result * 37 + (game_result != null ? game_result.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<GamePktownGameResult> {

    public RouteInfo route_info;
    public String game_name;
    public String icon_url;
    public Integer game_policy;
    public List<GamePktownPlayerData> player_datas;
    public String game_jump_url;
    public GameResult game_result;

    public Builder() {
    }

    public Builder(GamePktownGameResult message) {
      super(message);
      if (message == null) return;
      this.route_info = message.route_info;
      this.game_name = message.game_name;
      this.icon_url = message.icon_url;
      this.game_policy = message.game_policy;
      this.player_datas = copyOf(message.player_datas);
      this.game_jump_url = message.game_jump_url;
      this.game_result = message.game_result;
    }

    public Builder route_info(RouteInfo route_info) {
      this.route_info = route_info;
      return this;
    }

    /**
     * 路由信息
     */
    public Builder game_name(String game_name) {
      this.game_name = game_name;
      return this;
    }

    /**
     * 游戏名
     */
    public Builder icon_url(String icon_url) {
      this.icon_url = icon_url;
      return this;
    }

    /**
     * 游戏图标
     */
    public Builder game_policy(Integer game_policy) {
      this.game_policy = game_policy;
      return this;
    }

    /**
     * 游戏策略
     */
    public Builder player_datas(List<GamePktownPlayerData> player_datas) {
      this.player_datas = checkForNulls(player_datas);
      return this;
    }

    /**
     * 每个玩家的结果
     */
    public Builder game_jump_url(String game_jump_url) {
      this.game_jump_url = game_jump_url;
      return this;
    }

    /**
     * 游戏跳转url
     */
    public Builder game_result(GameResult game_result) {
      this.game_result = game_result;
      return this;
    }

    @Override
    public GamePktownGameResult build() {
      return new GamePktownGameResult(this);
    }
  }
}
