// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\game_pktown.proto
package com.wesocial.apollo.protocol.protobuf.game_pktown;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.INT32;
import static com.squareup.wire.Message.Datatype.UINT64;

/**
 * /////////////////////////////////////////////////////////////////////////////
 * 2. DO_GAME_COMMAND游戏命令
 * 2.1 GAME_PKTOWN_CMD_TYPE_UPDATE_SCORE
 */
public final class GamePktownUpdateScoreReqBuf extends Message {
  private static final long serialVersionUID = 0L;

  public static final Integer DEFAULT_SCORE = 0;
  public static final Integer DEFAULT_VERSION = 0;
  public static final Long DEFAULT_TIMESTAMP = 0L;

  @ProtoField(tag = 1, type = INT32)
  public final Integer score;

  /**
   * 玩家分数
   */
  @ProtoField(tag = 2, type = INT32)
  public final Integer version;

  /**
   * 版本号（客户端自增）
   */
  @ProtoField(tag = 3, type = UINT64)
  public final Long timestamp;

  public GamePktownUpdateScoreReqBuf(Integer score, Integer version, Long timestamp) {
    this.score = score;
    this.version = version;
    this.timestamp = timestamp;
  }

  private GamePktownUpdateScoreReqBuf(Builder builder) {
    this(builder.score, builder.version, builder.timestamp);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof GamePktownUpdateScoreReqBuf)) return false;
    GamePktownUpdateScoreReqBuf o = (GamePktownUpdateScoreReqBuf) other;
    return equals(score, o.score)
        && equals(version, o.version)
        && equals(timestamp, o.timestamp);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = score != null ? score.hashCode() : 0;
      result = result * 37 + (version != null ? version.hashCode() : 0);
      result = result * 37 + (timestamp != null ? timestamp.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<GamePktownUpdateScoreReqBuf> {

    public Integer score;
    public Integer version;
    public Long timestamp;

    public Builder() {
    }

    public Builder(GamePktownUpdateScoreReqBuf message) {
      super(message);
      if (message == null) return;
      this.score = message.score;
      this.version = message.version;
      this.timestamp = message.timestamp;
    }

    public Builder score(Integer score) {
      this.score = score;
      return this;
    }

    /**
     * 玩家分数
     */
    public Builder version(Integer version) {
      this.version = version;
      return this;
    }

    /**
     * 版本号（客户端自增）
     */
    public Builder timestamp(Long timestamp) {
      this.timestamp = timestamp;
      return this;
    }

    @Override
    public GamePktownUpdateScoreReqBuf build() {
      return new GamePktownUpdateScoreReqBuf(this);
    }
  }
}
