// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\game.proto
package com.wesocial.apollo.protocol.protobuf.game;

import com.squareup.wire.ProtoEnum;

public enum GameStatus
    implements ProtoEnum {
  GAME_STATUS_NONE(1),
  /**
   * 游戏不存在
   */
  GAME_STATUS_IDLE(2),
  /**
   * 游戏处于空闲状态
   */
  GAME_STATUS_PREPARE(3),
  /**
   * 游戏处于准备状态
   */
  GAME_STATUS_PLAYING(4),
  /**
   * 游戏正在进行中
   */
  GAME_STATUS_GAME_OVER(5);

  private final int value;

  private GameStatus(int value) {
    this.value = value;
  }

  @Override
  public int getValue() {
    return value;
  }
}
