// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\game.proto
package com.wesocial.apollo.protocol.protobuf.game;

import com.squareup.wire.ProtoEnum;

public enum GameEventType
    implements ProtoEnum {
  EVENT_TYPE_USER_EVENT(1),
  /**
   * 用户事件
   */
  EVENT_TYPE_TIME_OUT_EVENT(2),
  /**
   * 超时事件
   */
  EVENT_TYPE_MANUAL_EVENT(3);

  private final int value;

  private GameEventType(int value) {
    this.value = value;
  }

  @Override
  public int getValue() {
    return value;
  }
}
