// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\game.proto
package com.wesocial.apollo.protocol.protobuf.game;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;
import okio.ByteString;

import static com.squareup.wire.Message.Datatype.BYTES;
import static com.squareup.wire.Message.Datatype.UINT64;

public final class GetGameDataRsp extends Message {
  private static final long serialVersionUID = 0L;

  public static final ByteString DEFAULT_RESERVED_BUF = ByteString.EMPTY;
  public static final ByteString DEFAULT_GAME_RSP_BUF = ByteString.EMPTY;
  public static final Long DEFAULT_SEQ_NO = 0L;

  @ProtoField(tag = 1, type = BYTES)
  public final ByteString reserved_buf;

  /**
   * 服务端使用，客户端忽略
   */
  @ProtoField(tag = 2, type = BYTES)
  public final ByteString game_rsp_buf;

  /**
   * 游戏逻辑数据
   */
  @ProtoField(tag = 3, type = UINT64)
  public final Long seq_no;

  public GetGameDataRsp(ByteString reserved_buf, ByteString game_rsp_buf, Long seq_no) {
    this.reserved_buf = reserved_buf;
    this.game_rsp_buf = game_rsp_buf;
    this.seq_no = seq_no;
  }

  private GetGameDataRsp(Builder builder) {
    this(builder.reserved_buf, builder.game_rsp_buf, builder.seq_no);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof GetGameDataRsp)) return false;
    GetGameDataRsp o = (GetGameDataRsp) other;
    return equals(reserved_buf, o.reserved_buf)
        && equals(game_rsp_buf, o.game_rsp_buf)
        && equals(seq_no, o.seq_no);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = reserved_buf != null ? reserved_buf.hashCode() : 0;
      result = result * 37 + (game_rsp_buf != null ? game_rsp_buf.hashCode() : 0);
      result = result * 37 + (seq_no != null ? seq_no.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<GetGameDataRsp> {

    public ByteString reserved_buf;
    public ByteString game_rsp_buf;
    public Long seq_no;

    public Builder() {
    }

    public Builder(GetGameDataRsp message) {
      super(message);
      if (message == null) return;
      this.reserved_buf = message.reserved_buf;
      this.game_rsp_buf = message.game_rsp_buf;
      this.seq_no = message.seq_no;
    }

    public Builder reserved_buf(ByteString reserved_buf) {
      this.reserved_buf = reserved_buf;
      return this;
    }

    /**
     * 服务端使用，客户端忽略
     */
    public Builder game_rsp_buf(ByteString game_rsp_buf) {
      this.game_rsp_buf = game_rsp_buf;
      return this;
    }

    /**
     * 游戏逻辑数据
     */
    public Builder seq_no(Long seq_no) {
      this.seq_no = seq_no;
      return this;
    }

    @Override
    public GetGameDataRsp build() {
      return new GetGameDataRsp(this);
    }
  }
}
