// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\game.proto
package com.wesocial.apollo.protocol.protobuf.game;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;
import okio.ByteString;

import static com.squareup.wire.Message.Datatype.BYTES;
import static com.squareup.wire.Message.Datatype.INT32;
import static com.squareup.wire.Message.Datatype.UINT64;

/**
 * //////////////////////////////////////////////////////////////////////////////
 * 2. 读取游戏数据
 * cmd = GET_GAME_DATA
 */
public final class GetGameDataReq extends Message {
  private static final long serialVersionUID = 0L;

  public static final ByteString DEFAULT_RESERVED_BUF = ByteString.EMPTY;
  public static final ByteString DEFAULT_GAME_REQ_BUF = ByteString.EMPTY;
  public static final Integer DEFAULT_BUF_TYPE = 0;
  public static final Long DEFAULT_SEQ_NO = 0L;

  @ProtoField(tag = 1, type = BYTES)
  public final ByteString reserved_buf;

  /**
   * 服务端使用，客户端忽略
   */
  @ProtoField(tag = 2, type = BYTES)
  public final ByteString game_req_buf;

  /**
   * 游戏逻辑数据
   */
  @ProtoField(tag = 3, type = INT32)
  public final Integer buf_type;

  /**
   * game_req_buf格式：1-pb，2-json
   */
  @ProtoField(tag = 4)
  public final RouteInfo route_info;

  /**
   * 路由信息
   */
  @ProtoField(tag = 5, type = UINT64)
  public final Long seq_no;

  public GetGameDataReq(ByteString reserved_buf, ByteString game_req_buf, Integer buf_type, RouteInfo route_info, Long seq_no) {
    this.reserved_buf = reserved_buf;
    this.game_req_buf = game_req_buf;
    this.buf_type = buf_type;
    this.route_info = route_info;
    this.seq_no = seq_no;
  }

  private GetGameDataReq(Builder builder) {
    this(builder.reserved_buf, builder.game_req_buf, builder.buf_type, builder.route_info, builder.seq_no);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof GetGameDataReq)) return false;
    GetGameDataReq o = (GetGameDataReq) other;
    return equals(reserved_buf, o.reserved_buf)
        && equals(game_req_buf, o.game_req_buf)
        && equals(buf_type, o.buf_type)
        && equals(route_info, o.route_info)
        && equals(seq_no, o.seq_no);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = reserved_buf != null ? reserved_buf.hashCode() : 0;
      result = result * 37 + (game_req_buf != null ? game_req_buf.hashCode() : 0);
      result = result * 37 + (buf_type != null ? buf_type.hashCode() : 0);
      result = result * 37 + (route_info != null ? route_info.hashCode() : 0);
      result = result * 37 + (seq_no != null ? seq_no.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<GetGameDataReq> {

    public ByteString reserved_buf;
    public ByteString game_req_buf;
    public Integer buf_type;
    public RouteInfo route_info;
    public Long seq_no;

    public Builder() {
    }

    public Builder(GetGameDataReq message) {
      super(message);
      if (message == null) return;
      this.reserved_buf = message.reserved_buf;
      this.game_req_buf = message.game_req_buf;
      this.buf_type = message.buf_type;
      this.route_info = message.route_info;
      this.seq_no = message.seq_no;
    }

    public Builder reserved_buf(ByteString reserved_buf) {
      this.reserved_buf = reserved_buf;
      return this;
    }

    /**
     * 服务端使用，客户端忽略
     */
    public Builder game_req_buf(ByteString game_req_buf) {
      this.game_req_buf = game_req_buf;
      return this;
    }

    /**
     * 游戏逻辑数据
     */
    public Builder buf_type(Integer buf_type) {
      this.buf_type = buf_type;
      return this;
    }

    /**
     * game_req_buf格式：1-pb，2-json
     */
    public Builder route_info(RouteInfo route_info) {
      this.route_info = route_info;
      return this;
    }

    /**
     * 路由信息
     */
    public Builder seq_no(Long seq_no) {
      this.seq_no = seq_no;
      return this;
    }

    @Override
    public GetGameDataReq build() {
      return new GetGameDataReq(this);
    }
  }
}
