// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\game.proto
package com.wesocial.apollo.protocol.protobuf.game;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.INT32;
import static com.squareup.wire.Message.Datatype.INT64;

/**
 * -----------------------------------------------------------------------------
 * 客户端和服务端交互协议
 * -----------------------------------------------------------------------------
 * //////////////////////////////////////////////////////////////////////////////
 * 基础结构
 * //////////////////////////////////////////////////////////////////////////////
 * 路由信息
 */
public final class RouteInfo extends Message {
  private static final long serialVersionUID = 0L;

  public static final Integer DEFAULT_SERVER_ID = 0;
  public static final Integer DEFAULT_GAME_ID = 0;
  public static final Integer DEFAULT_TABLE_ID = 0;
  public static final Long DEFAULT_TABLE_SEQ = 0L;

  @ProtoField(tag = 1, type = INT32)
  public final Integer server_id;

  /**
   * game_server id
   */
  @ProtoField(tag = 2, type = INT32)
  public final Integer game_id;

  /**
   * 游戏ID
   */
  @ProtoField(tag = 3, type = INT32)
  public final Integer table_id;

  /**
   * 桌子编号
   */
  @ProtoField(tag = 4, type = INT64)
  public final Long table_seq;

  public RouteInfo(Integer server_id, Integer game_id, Integer table_id, Long table_seq) {
    this.server_id = server_id;
    this.game_id = game_id;
    this.table_id = table_id;
    this.table_seq = table_seq;
  }

  private RouteInfo(Builder builder) {
    this(builder.server_id, builder.game_id, builder.table_id, builder.table_seq);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof RouteInfo)) return false;
    RouteInfo o = (RouteInfo) other;
    return equals(server_id, o.server_id)
        && equals(game_id, o.game_id)
        && equals(table_id, o.table_id)
        && equals(table_seq, o.table_seq);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = server_id != null ? server_id.hashCode() : 0;
      result = result * 37 + (game_id != null ? game_id.hashCode() : 0);
      result = result * 37 + (table_id != null ? table_id.hashCode() : 0);
      result = result * 37 + (table_seq != null ? table_seq.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<RouteInfo> {

    public Integer server_id;
    public Integer game_id;
    public Integer table_id;
    public Long table_seq;

    public Builder() {
    }

    public Builder(RouteInfo message) {
      super(message);
      if (message == null) return;
      this.server_id = message.server_id;
      this.game_id = message.game_id;
      this.table_id = message.table_id;
      this.table_seq = message.table_seq;
    }

    public Builder server_id(Integer server_id) {
      this.server_id = server_id;
      return this;
    }

    /**
     * game_server id
     */
    public Builder game_id(Integer game_id) {
      this.game_id = game_id;
      return this;
    }

    /**
     * 游戏ID
     */
    public Builder table_id(Integer table_id) {
      this.table_id = table_id;
      return this;
    }

    /**
     * 桌子编号
     */
    public Builder table_seq(Long table_seq) {
      this.table_seq = table_seq;
      return this;
    }

    @Override
    public RouteInfo build() {
      return new RouteInfo(this);
    }
  }
}
